// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package github_com_qeeqez_api_db_sqlc
type VideoQuality int

const (
    BASIC_VIDEOQUALITY VideoQuality = iota
    SHORTS_VIDEOQUALITY
    PRO_VIDEOQUALITY
)

func (i VideoQuality) String() string {
    return []string{"basic", "shorts", "pro"}[i]
}
func ParseVideoQuality(v string) (any, error) {
    result := BASIC_VIDEOQUALITY
    switch v {
        case "basic":
            result = BASIC_VIDEOQUALITY
        case "shorts":
            result = SHORTS_VIDEOQUALITY
        case "pro":
            result = PRO_VIDEOQUALITY
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeVideoQuality(values []VideoQuality) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i VideoQuality) isMultiValue() bool {
    return false
}
