/*
RIXL API

**Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.

API version: 2.0
Contact: support@rixl.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package images

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// PostImagesUploadInitRequest - struct for PostImagesUploadInitRequest
type PostImagesUploadInitRequest struct {
	InternalImagesHandlerUploadInitRequest *InternalImagesHandlerUploadInitRequest
	MapmapOfStringAny *map[string]interface{}
}

// InternalImagesHandlerUploadInitRequestAsPostImagesUploadInitRequest is a convenience function that returns InternalImagesHandlerUploadInitRequest wrapped in PostImagesUploadInitRequest
func InternalImagesHandlerUploadInitRequestAsPostImagesUploadInitRequest(v *InternalImagesHandlerUploadInitRequest) PostImagesUploadInitRequest {
	return PostImagesUploadInitRequest{
		InternalImagesHandlerUploadInitRequest: v,
	}
}

// map[string]interface{}AsPostImagesUploadInitRequest is a convenience function that returns map[string]interface{} wrapped in PostImagesUploadInitRequest
func MapmapOfStringAnyAsPostImagesUploadInitRequest(v *map[string]interface{}) PostImagesUploadInitRequest {
	return PostImagesUploadInitRequest{
		MapmapOfStringAny: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *PostImagesUploadInitRequest) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into InternalImagesHandlerUploadInitRequest
	err = newStrictDecoder(data).Decode(&dst.InternalImagesHandlerUploadInitRequest)
	if err == nil {
		jsonInternalImagesHandlerUploadInitRequest, _ := json.Marshal(dst.InternalImagesHandlerUploadInitRequest)
		if string(jsonInternalImagesHandlerUploadInitRequest) == "{}" { // empty struct
			dst.InternalImagesHandlerUploadInitRequest = nil
		} else {
			if err = validator.Validate(dst.InternalImagesHandlerUploadInitRequest); err != nil {
				dst.InternalImagesHandlerUploadInitRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.InternalImagesHandlerUploadInitRequest = nil
	}

	// try to unmarshal data into MapmapOfStringAny
	err = newStrictDecoder(data).Decode(&dst.MapmapOfStringAny)
	if err == nil {
		jsonMapmapOfStringAny, _ := json.Marshal(dst.MapmapOfStringAny)
		if string(jsonMapmapOfStringAny) == "{}" { // empty struct
			dst.MapmapOfStringAny = nil
		} else {
			if err = validator.Validate(dst.MapmapOfStringAny); err != nil {
				dst.MapmapOfStringAny = nil
			} else {
				match++
			}
		}
	} else {
		dst.MapmapOfStringAny = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.InternalImagesHandlerUploadInitRequest = nil
		dst.MapmapOfStringAny = nil

		return fmt.Errorf("data matches more than one schema in oneOf(PostImagesUploadInitRequest)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(PostImagesUploadInitRequest)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src PostImagesUploadInitRequest) MarshalJSON() ([]byte, error) {
	if src.InternalImagesHandlerUploadInitRequest != nil {
		return json.Marshal(&src.InternalImagesHandlerUploadInitRequest)
	}

	if src.MapmapOfStringAny != nil {
		return json.Marshal(&src.MapmapOfStringAny)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *PostImagesUploadInitRequest) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.InternalImagesHandlerUploadInitRequest != nil {
		return obj.InternalImagesHandlerUploadInitRequest
	}

	if obj.MapmapOfStringAny != nil {
		return obj.MapmapOfStringAny
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj PostImagesUploadInitRequest) GetActualInstanceValue() (interface{}) {
	if obj.InternalImagesHandlerUploadInitRequest != nil {
		return *obj.InternalImagesHandlerUploadInitRequest
	}

	if obj.MapmapOfStringAny != nil {
		return *obj.MapmapOfStringAny
	}

	// all schemas are nil
	return nil
}

type NullablePostImagesUploadInitRequest struct {
	value *PostImagesUploadInitRequest
	isSet bool
}

func (v NullablePostImagesUploadInitRequest) Get() *PostImagesUploadInitRequest {
	return v.value
}

func (v *NullablePostImagesUploadInitRequest) Set(val *PostImagesUploadInitRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePostImagesUploadInitRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePostImagesUploadInitRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostImagesUploadInitRequest(val *PostImagesUploadInitRequest) *NullablePostImagesUploadInitRequest {
	return &NullablePostImagesUploadInitRequest{value: val, isSet: true}
}

func (v NullablePostImagesUploadInitRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostImagesUploadInitRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


