// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package github_com_qeeqez_api_internal_videos_handler_upload

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type InitResponse struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The poster_id property
    poster_id *string
    // The poster_presigned_url property
    poster_presigned_url *string
    // The upload_expires property
    upload_expires *int32
    // The video_id property
    video_id *string
    // The video_presigned_url property
    video_presigned_url *string
}
// NewInitResponse instantiates a new InitResponse and sets the default values.
func NewInitResponse()(*InitResponse) {
    m := &InitResponse{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateInitResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateInitResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewInitResponse(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *InitResponse) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *InitResponse) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["poster_id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPosterId(val)
        }
        return nil
    }
    res["poster_presigned_url"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPosterPresignedUrl(val)
        }
        return nil
    }
    res["upload_expires"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetUploadExpires(val)
        }
        return nil
    }
    res["video_id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetVideoId(val)
        }
        return nil
    }
    res["video_presigned_url"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetVideoPresignedUrl(val)
        }
        return nil
    }
    return res
}
// GetPosterId gets the poster_id property value. The poster_id property
// returns a *string when successful
func (m *InitResponse) GetPosterId()(*string) {
    return m.poster_id
}
// GetPosterPresignedUrl gets the poster_presigned_url property value. The poster_presigned_url property
// returns a *string when successful
func (m *InitResponse) GetPosterPresignedUrl()(*string) {
    return m.poster_presigned_url
}
// GetUploadExpires gets the upload_expires property value. The upload_expires property
// returns a *int32 when successful
func (m *InitResponse) GetUploadExpires()(*int32) {
    return m.upload_expires
}
// GetVideoId gets the video_id property value. The video_id property
// returns a *string when successful
func (m *InitResponse) GetVideoId()(*string) {
    return m.video_id
}
// GetVideoPresignedUrl gets the video_presigned_url property value. The video_presigned_url property
// returns a *string when successful
func (m *InitResponse) GetVideoPresignedUrl()(*string) {
    return m.video_presigned_url
}
// Serialize serializes information the current object
func (m *InitResponse) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("poster_id", m.GetPosterId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("poster_presigned_url", m.GetPosterPresignedUrl())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("upload_expires", m.GetUploadExpires())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("video_id", m.GetVideoId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("video_presigned_url", m.GetVideoPresignedUrl())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *InitResponse) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetPosterId sets the poster_id property value. The poster_id property
func (m *InitResponse) SetPosterId(value *string)() {
    m.poster_id = value
}
// SetPosterPresignedUrl sets the poster_presigned_url property value. The poster_presigned_url property
func (m *InitResponse) SetPosterPresignedUrl(value *string)() {
    m.poster_presigned_url = value
}
// SetUploadExpires sets the upload_expires property value. The upload_expires property
func (m *InitResponse) SetUploadExpires(value *int32)() {
    m.upload_expires = value
}
// SetVideoId sets the video_id property value. The video_id property
func (m *InitResponse) SetVideoId(value *string)() {
    m.video_id = value
}
// SetVideoPresignedUrl sets the video_presigned_url property value. The video_presigned_url property
func (m *InitResponse) SetVideoPresignedUrl(value *string)() {
    m.video_presigned_url = value
}
type InitResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetPosterId()(*string)
    GetPosterPresignedUrl()(*string)
    GetUploadExpires()(*int32)
    GetVideoId()(*string)
    GetVideoPresignedUrl()(*string)
    SetPosterId(value *string)()
    SetPosterPresignedUrl(value *string)()
    SetUploadExpires(value *int32)()
    SetVideoId(value *string)()
    SetVideoPresignedUrl(value *string)()
}
