// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package github_com_rixlhq_api_db_sqlc
type PlanType int

const (
    FREE_PLANTYPE PlanType = iota
    PRO_PLANTYPE
    CUSTOM_PLANTYPE
    PAY_AS_YOU_GO_PLANTYPE
)

func (i PlanType) String() string {
    return []string{"free", "pro", "custom", "pay_as_you_go"}[i]
}
func ParsePlanType(v string) (any, error) {
    result := FREE_PLANTYPE
    switch v {
        case "free":
            result = FREE_PLANTYPE
        case "pro":
            result = PRO_PLANTYPE
        case "custom":
            result = CUSTOM_PLANTYPE
        case "pay_as_you_go":
            result = PAY_AS_YOU_GO_PLANTYPE
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializePlanType(values []PlanType) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i PlanType) isMultiValue() bool {
    return false
}
