// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package videos

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type ItemAudioTracksItemWithLang_codePutRequestBody struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The file property
    file []byte
    // The label property
    label *string
}
// NewItemAudioTracksItemWithLang_codePutRequestBody instantiates a new ItemAudioTracksItemWithLang_codePutRequestBody and sets the default values.
func NewItemAudioTracksItemWithLang_codePutRequestBody()(*ItemAudioTracksItemWithLang_codePutRequestBody) {
    m := &ItemAudioTracksItemWithLang_codePutRequestBody{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateItemAudioTracksItemWithLang_codePutRequestBodyFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateItemAudioTracksItemWithLang_codePutRequestBodyFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemAudioTracksItemWithLang_codePutRequestBody(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *ItemAudioTracksItemWithLang_codePutRequestBody) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *ItemAudioTracksItemWithLang_codePutRequestBody) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["file"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetByteArrayValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetFile(val)
        }
        return nil
    }
    res["label"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLabel(val)
        }
        return nil
    }
    return res
}
// GetFile gets the file property value. The file property
// returns a []byte when successful
func (m *ItemAudioTracksItemWithLang_codePutRequestBody) GetFile()([]byte) {
    return m.file
}
// GetLabel gets the label property value. The label property
// returns a *string when successful
func (m *ItemAudioTracksItemWithLang_codePutRequestBody) GetLabel()(*string) {
    return m.label
}
// Serialize serializes information the current object
func (m *ItemAudioTracksItemWithLang_codePutRequestBody) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteByteArrayValue("file", m.GetFile())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("label", m.GetLabel())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *ItemAudioTracksItemWithLang_codePutRequestBody) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetFile sets the file property value. The file property
func (m *ItemAudioTracksItemWithLang_codePutRequestBody) SetFile(value []byte)() {
    m.file = value
}
// SetLabel sets the label property value. The label property
func (m *ItemAudioTracksItemWithLang_codePutRequestBody) SetLabel(value *string)() {
    m.label = value
}
type ItemAudioTracksItemWithLang_codePutRequestBodyable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetFile()([]byte)
    GetLabel()(*string)
    SetFile(value []byte)()
    SetLabel(value *string)()
}
