// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package videos

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i6a8119714aaa1c348f0ce22bc9a01a8501620888990eb654e94c882e51a080ed "github.com/qeeqez/rixl-sdk-go/sdk/models"
)

// ItemAudioTracksRequestBuilder builds and executes requests for operations under \videos\{videoId}\audio-tracks
type ItemAudioTracksRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// ByLang_code gets an item from the github.com/qeeqez/rixl-sdk-go/sdk.videos.item.audioTracks.item collection
// returns a *ItemAudioTracksWithLang_codeItemRequestBuilder when successful
func (m *ItemAudioTracksRequestBuilder) ByLang_code(lang_code string)(*ItemAudioTracksWithLang_codeItemRequestBuilder) {
    urlTplParams := make(map[string]string)
    for idx, item := range m.BaseRequestBuilder.PathParameters {
        urlTplParams[idx] = item
    }
    if lang_code != "" {
        urlTplParams["lang_code"] = lang_code
    }
    return NewItemAudioTracksWithLang_codeItemRequestBuilderInternal(urlTplParams, m.BaseRequestBuilder.RequestAdapter)
}
// NewItemAudioTracksRequestBuilderInternal instantiates a new ItemAudioTracksRequestBuilder and sets the default values.
func NewItemAudioTracksRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*ItemAudioTracksRequestBuilder) {
    m := &ItemAudioTracksRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/videos/{videoId}/audio-tracks", pathParameters),
    }
    return m
}
// NewItemAudioTracksRequestBuilder instantiates a new ItemAudioTracksRequestBuilder and sets the default values.
func NewItemAudioTracksRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*ItemAudioTracksRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewItemAudioTracksRequestBuilderInternal(urlParams, requestAdapter)
}
// Delete remove all additional audio tracks from a video using API key authentication
// returns a AudioTrackDeleteable when successful
func (m *ItemAudioTracksRequestBuilder) Delete(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DefaultQueryParameters])(i6a8119714aaa1c348f0ce22bc9a01a8501620888990eb654e94c882e51a080ed.AudioTrackDeleteable, error) {
    requestInfo, err := m.ToDeleteRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, i6a8119714aaa1c348f0ce22bc9a01a8501620888990eb654e94c882e51a080ed.CreateAudioTrackDeleteFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(i6a8119714aaa1c348f0ce22bc9a01a8501620888990eb654e94c882e51a080ed.AudioTrackDeleteable), nil
}
// ToDeleteRequestInformation remove all additional audio tracks from a video using API key authentication
// returns a *RequestInformation when successful
func (m *ItemAudioTracksRequestBuilder) ToDeleteRequestInformation(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DefaultQueryParameters])(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DELETE, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ConfigureRequestInformation(requestInfo, requestConfiguration)
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *ItemAudioTracksRequestBuilder when successful
func (m *ItemAudioTracksRequestBuilder) WithUrl(rawUrl string)(*ItemAudioTracksRequestBuilder) {
    return NewItemAudioTracksRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
