// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package videos

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i14c1aa900e4320bbc3246d488d9c4da70829934f11cfe18376f0e3789cdfc0d1 "github.com/rixlhq/rixl-go/sdk/models/internal_videos_handler_subtitles"
)

// LanguagesRequestBuilder builds and executes requests for operations under \videos\languages
type LanguagesRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// NewLanguagesRequestBuilderInternal instantiates a new LanguagesRequestBuilder and sets the default values.
func NewLanguagesRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*LanguagesRequestBuilder) {
    m := &LanguagesRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/videos/languages", pathParameters),
    }
    return m
}
// NewLanguagesRequestBuilder instantiates a new LanguagesRequestBuilder and sets the default values.
func NewLanguagesRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*LanguagesRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewLanguagesRequestBuilderInternal(urlParams, requestAdapter)
}
// Get get list of supported languages for subtitles
// returns a []LanguageResponseable when successful
func (m *LanguagesRequestBuilder) Get(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DefaultQueryParameters])([]i14c1aa900e4320bbc3246d488d9c4da70829934f11cfe18376f0e3789cdfc0d1.LanguageResponseable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.SendCollection(ctx, requestInfo, i14c1aa900e4320bbc3246d488d9c4da70829934f11cfe18376f0e3789cdfc0d1.CreateLanguageResponseFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    val := make([]i14c1aa900e4320bbc3246d488d9c4da70829934f11cfe18376f0e3789cdfc0d1.LanguageResponseable, len(res))
    for i, v := range res {
        if v != nil {
            val[i] = v.(i14c1aa900e4320bbc3246d488d9c4da70829934f11cfe18376f0e3789cdfc0d1.LanguageResponseable)
        }
    }
    return val, nil
}
// ToGetRequestInformation get list of supported languages for subtitles
// returns a *RequestInformation when successful
func (m *LanguagesRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DefaultQueryParameters])(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ConfigureRequestInformation(requestInfo, requestConfiguration)
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *LanguagesRequestBuilder when successful
func (m *LanguagesRequestBuilder) WithUrl(rawUrl string)(*LanguagesRequestBuilder) {
    return NewLanguagesRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
