/*
RIXL API

**Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.

API version: 2.0
Contact: support@rixl.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package videos

import (
	"encoding/json"
)

// checks if the PaginationPaginatedResponseVideo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginationPaginatedResponseVideo{}

// PaginationPaginatedResponseVideo struct for PaginationPaginatedResponseVideo
type PaginationPaginatedResponseVideo struct {
	// Data contains the slice of items for the current request.
	Data []Video `json:"data,omitempty"`
	// Pagination data for the request.
	Pagination *PaginationPagination `json:"pagination,omitempty"`
}

// NewPaginationPaginatedResponseVideo instantiates a new PaginationPaginatedResponseVideo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginationPaginatedResponseVideo() *PaginationPaginatedResponseVideo {
	this := PaginationPaginatedResponseVideo{}
	return &this
}

// NewPaginationPaginatedResponseVideoWithDefaults instantiates a new PaginationPaginatedResponseVideo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginationPaginatedResponseVideoWithDefaults() *PaginationPaginatedResponseVideo {
	this := PaginationPaginatedResponseVideo{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *PaginationPaginatedResponseVideo) GetData() []Video {
	if o == nil || IsNil(o.Data) {
		var ret []Video
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginationPaginatedResponseVideo) GetDataOk() ([]Video, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *PaginationPaginatedResponseVideo) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []Video and assigns it to the Data field.
func (o *PaginationPaginatedResponseVideo) SetData(v []Video) {
	o.Data = v
}

// GetPagination returns the Pagination field value if set, zero value otherwise.
func (o *PaginationPaginatedResponseVideo) GetPagination() PaginationPagination {
	if o == nil || IsNil(o.Pagination) {
		var ret PaginationPagination
		return ret
	}
	return *o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginationPaginatedResponseVideo) GetPaginationOk() (*PaginationPagination, bool) {
	if o == nil || IsNil(o.Pagination) {
		return nil, false
	}
	return o.Pagination, true
}

// HasPagination returns a boolean if a field has been set.
func (o *PaginationPaginatedResponseVideo) HasPagination() bool {
	if o != nil && !IsNil(o.Pagination) {
		return true
	}

	return false
}

// SetPagination gets a reference to the given PaginationPagination and assigns it to the Pagination field.
func (o *PaginationPaginatedResponseVideo) SetPagination(v PaginationPagination) {
	o.Pagination = &v
}

func (o PaginationPaginatedResponseVideo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginationPaginatedResponseVideo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Pagination) {
		toSerialize["pagination"] = o.Pagination
	}
	return toSerialize, nil
}

type NullablePaginationPaginatedResponseVideo struct {
	value *PaginationPaginatedResponseVideo
	isSet bool
}

func (v NullablePaginationPaginatedResponseVideo) Get() *PaginationPaginatedResponseVideo {
	return v.value
}

func (v *NullablePaginationPaginatedResponseVideo) Set(val *PaginationPaginatedResponseVideo) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginationPaginatedResponseVideo) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginationPaginatedResponseVideo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginationPaginatedResponseVideo(val *PaginationPaginatedResponseVideo) *NullablePaginationPaginatedResponseVideo {
	return &NullablePaginationPaginatedResponseVideo{value: val, isSet: true}
}

func (v NullablePaginationPaginatedResponseVideo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginationPaginatedResponseVideo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


