/*
RIXL API

**Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.

API version: 2.0
Contact: support@rixl.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package videos

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// PutVideosVideoIdChaptersRequest - struct for PutVideosVideoIdChaptersRequest
type PutVideosVideoIdChaptersRequest struct {
	UpdateChaptersRequest *UpdateChaptersRequest
	MapmapOfStringAny *map[string]interface{}
}

// UpdateChaptersRequestAsPutVideosVideoIdChaptersRequest is a convenience function that returns UpdateChaptersRequest wrapped in PutVideosVideoIdChaptersRequest
func UpdateChaptersRequestAsPutVideosVideoIdChaptersRequest(v *UpdateChaptersRequest) PutVideosVideoIdChaptersRequest {
	return PutVideosVideoIdChaptersRequest{
		UpdateChaptersRequest: v,
	}
}

// map[string]interface{}AsPutVideosVideoIdChaptersRequest is a convenience function that returns map[string]interface{} wrapped in PutVideosVideoIdChaptersRequest
func MapmapOfStringAnyAsPutVideosVideoIdChaptersRequest(v *map[string]interface{}) PutVideosVideoIdChaptersRequest {
	return PutVideosVideoIdChaptersRequest{
		MapmapOfStringAny: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *PutVideosVideoIdChaptersRequest) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into UpdateChaptersRequest
	err = newStrictDecoder(data).Decode(&dst.UpdateChaptersRequest)
	if err == nil {
		jsonUpdateChaptersRequest, _ := json.Marshal(dst.UpdateChaptersRequest)
		if string(jsonUpdateChaptersRequest) == "{}" { // empty struct
			dst.UpdateChaptersRequest = nil
		} else {
			if err = validator.Validate(dst.UpdateChaptersRequest); err != nil {
				dst.UpdateChaptersRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.UpdateChaptersRequest = nil
	}

	// try to unmarshal data into MapmapOfStringAny
	err = newStrictDecoder(data).Decode(&dst.MapmapOfStringAny)
	if err == nil {
		jsonMapmapOfStringAny, _ := json.Marshal(dst.MapmapOfStringAny)
		if string(jsonMapmapOfStringAny) == "{}" { // empty struct
			dst.MapmapOfStringAny = nil
		} else {
			if err = validator.Validate(dst.MapmapOfStringAny); err != nil {
				dst.MapmapOfStringAny = nil
			} else {
				match++
			}
		}
	} else {
		dst.MapmapOfStringAny = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.UpdateChaptersRequest = nil
		dst.MapmapOfStringAny = nil

		return fmt.Errorf("data matches more than one schema in oneOf(PutVideosVideoIdChaptersRequest)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(PutVideosVideoIdChaptersRequest)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src PutVideosVideoIdChaptersRequest) MarshalJSON() ([]byte, error) {
	if src.UpdateChaptersRequest != nil {
		return json.Marshal(&src.UpdateChaptersRequest)
	}

	if src.MapmapOfStringAny != nil {
		return json.Marshal(&src.MapmapOfStringAny)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *PutVideosVideoIdChaptersRequest) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.UpdateChaptersRequest != nil {
		return obj.UpdateChaptersRequest
	}

	if obj.MapmapOfStringAny != nil {
		return obj.MapmapOfStringAny
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj PutVideosVideoIdChaptersRequest) GetActualInstanceValue() (interface{}) {
	if obj.UpdateChaptersRequest != nil {
		return *obj.UpdateChaptersRequest
	}

	if obj.MapmapOfStringAny != nil {
		return *obj.MapmapOfStringAny
	}

	// all schemas are nil
	return nil
}

type NullablePutVideosVideoIdChaptersRequest struct {
	value *PutVideosVideoIdChaptersRequest
	isSet bool
}

func (v NullablePutVideosVideoIdChaptersRequest) Get() *PutVideosVideoIdChaptersRequest {
	return v.value
}

func (v *NullablePutVideosVideoIdChaptersRequest) Set(val *PutVideosVideoIdChaptersRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePutVideosVideoIdChaptersRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePutVideosVideoIdChaptersRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePutVideosVideoIdChaptersRequest(val *PutVideosVideoIdChaptersRequest) *NullablePutVideosVideoIdChaptersRequest {
	return &NullablePutVideosVideoIdChaptersRequest{value: val, isSet: true}
}

func (v NullablePutVideosVideoIdChaptersRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePutVideosVideoIdChaptersRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


