/*
RIXL API

**Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.

API version: 2.0
Contact: support@rixl.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package videos

import (
	"encoding/json"
)

// checks if the Image type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Image{}

// Image struct for Image
type Image struct {
	AttachedToVideo *bool `json:"attached_to_video,omitempty"`
	File *File `json:"file,omitempty"`
	Height *int32 `json:"height,omitempty"`
	Id *string `json:"id,omitempty"`
	Thumbhash *string `json:"thumbhash,omitempty"`
	Width *int32 `json:"width,omitempty"`
}

// NewImage instantiates a new Image object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImage() *Image {
	this := Image{}
	return &this
}

// NewImageWithDefaults instantiates a new Image object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImageWithDefaults() *Image {
	this := Image{}
	return &this
}

// GetAttachedToVideo returns the AttachedToVideo field value if set, zero value otherwise.
func (o *Image) GetAttachedToVideo() bool {
	if o == nil || IsNil(o.AttachedToVideo) {
		var ret bool
		return ret
	}
	return *o.AttachedToVideo
}

// GetAttachedToVideoOk returns a tuple with the AttachedToVideo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Image) GetAttachedToVideoOk() (*bool, bool) {
	if o == nil || IsNil(o.AttachedToVideo) {
		return nil, false
	}
	return o.AttachedToVideo, true
}

// HasAttachedToVideo returns a boolean if a field has been set.
func (o *Image) HasAttachedToVideo() bool {
	if o != nil && !IsNil(o.AttachedToVideo) {
		return true
	}

	return false
}

// SetAttachedToVideo gets a reference to the given bool and assigns it to the AttachedToVideo field.
func (o *Image) SetAttachedToVideo(v bool) {
	o.AttachedToVideo = &v
}

// GetFile returns the File field value if set, zero value otherwise.
func (o *Image) GetFile() File {
	if o == nil || IsNil(o.File) {
		var ret File
		return ret
	}
	return *o.File
}

// GetFileOk returns a tuple with the File field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Image) GetFileOk() (*File, bool) {
	if o == nil || IsNil(o.File) {
		return nil, false
	}
	return o.File, true
}

// HasFile returns a boolean if a field has been set.
func (o *Image) HasFile() bool {
	if o != nil && !IsNil(o.File) {
		return true
	}

	return false
}

// SetFile gets a reference to the given File and assigns it to the File field.
func (o *Image) SetFile(v File) {
	o.File = &v
}

// GetHeight returns the Height field value if set, zero value otherwise.
func (o *Image) GetHeight() int32 {
	if o == nil || IsNil(o.Height) {
		var ret int32
		return ret
	}
	return *o.Height
}

// GetHeightOk returns a tuple with the Height field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Image) GetHeightOk() (*int32, bool) {
	if o == nil || IsNil(o.Height) {
		return nil, false
	}
	return o.Height, true
}

// HasHeight returns a boolean if a field has been set.
func (o *Image) HasHeight() bool {
	if o != nil && !IsNil(o.Height) {
		return true
	}

	return false
}

// SetHeight gets a reference to the given int32 and assigns it to the Height field.
func (o *Image) SetHeight(v int32) {
	o.Height = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Image) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Image) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Image) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Image) SetId(v string) {
	o.Id = &v
}

// GetThumbhash returns the Thumbhash field value if set, zero value otherwise.
func (o *Image) GetThumbhash() string {
	if o == nil || IsNil(o.Thumbhash) {
		var ret string
		return ret
	}
	return *o.Thumbhash
}

// GetThumbhashOk returns a tuple with the Thumbhash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Image) GetThumbhashOk() (*string, bool) {
	if o == nil || IsNil(o.Thumbhash) {
		return nil, false
	}
	return o.Thumbhash, true
}

// HasThumbhash returns a boolean if a field has been set.
func (o *Image) HasThumbhash() bool {
	if o != nil && !IsNil(o.Thumbhash) {
		return true
	}

	return false
}

// SetThumbhash gets a reference to the given string and assigns it to the Thumbhash field.
func (o *Image) SetThumbhash(v string) {
	o.Thumbhash = &v
}

// GetWidth returns the Width field value if set, zero value otherwise.
func (o *Image) GetWidth() int32 {
	if o == nil || IsNil(o.Width) {
		var ret int32
		return ret
	}
	return *o.Width
}

// GetWidthOk returns a tuple with the Width field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Image) GetWidthOk() (*int32, bool) {
	if o == nil || IsNil(o.Width) {
		return nil, false
	}
	return o.Width, true
}

// HasWidth returns a boolean if a field has been set.
func (o *Image) HasWidth() bool {
	if o != nil && !IsNil(o.Width) {
		return true
	}

	return false
}

// SetWidth gets a reference to the given int32 and assigns it to the Width field.
func (o *Image) SetWidth(v int32) {
	o.Width = &v
}

func (o Image) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Image) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AttachedToVideo) {
		toSerialize["attached_to_video"] = o.AttachedToVideo
	}
	if !IsNil(o.File) {
		toSerialize["file"] = o.File
	}
	if !IsNil(o.Height) {
		toSerialize["height"] = o.Height
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Thumbhash) {
		toSerialize["thumbhash"] = o.Thumbhash
	}
	if !IsNil(o.Width) {
		toSerialize["width"] = o.Width
	}
	return toSerialize, nil
}

type NullableImage struct {
	value *Image
	isSet bool
}

func (v NullableImage) Get() *Image {
	return v.value
}

func (v *NullableImage) Set(val *Image) {
	v.value = val
	v.isSet = true
}

func (v NullableImage) IsSet() bool {
	return v.isSet
}

func (v *NullableImage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImage(val *Image) *NullableImage {
	return &NullableImage{value: val, isSet: true}
}

func (v NullableImage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


