// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package videos

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i90c0e1ee53825fe36252e17a45e5d3b5f64ca0be4b2c3a2284950d3439c0ff4d "github.com/rixlhq/rixl-go/sdk/models/github_com_rixlhq_api_internal_errors"
    if5fe6ebdb5303685c58216888d4b27c57bfc171364b5f0d7459d0af798f20bbf "github.com/rixlhq/rixl-go/sdk/models/pagination"
)

// VideosRequestBuilder builds and executes requests for operations under \videos
type VideosRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// VideosRequestBuilderGetQueryParameters retrieve all videos for a specific project, with pagination and sorting.
type VideosRequestBuilderGetQueryParameters struct {
    // Maximum number of items to return in a single request. <br> **Default:** `25`
    Limit *int32 `uriparametername:"limit"`
    // Starting point of the result set. <br>To get page 2 with a limit of 25, set `offset` to `25`. <br> **Default:** `0`
    Offset *int32 `uriparametername:"offset"`
    // Sort order (asc, desc)
    Order *string `uriparametername:"order"`
    // Field to sort by (created_at, name, size, updated_at, duration)
    Sort *string `uriparametername:"sort"`
}
// ByVideoId gets an item from the github.com/rixlhq/rixl-go/sdk.videos.item collection
// returns a *WithVideoItemRequestBuilder when successful
func (m *VideosRequestBuilder) ByVideoId(videoId string)(*WithVideoItemRequestBuilder) {
    urlTplParams := make(map[string]string)
    for idx, item := range m.BaseRequestBuilder.PathParameters {
        urlTplParams[idx] = item
    }
    if videoId != "" {
        urlTplParams["videoId"] = videoId
    }
    return NewWithVideoItemRequestBuilderInternal(urlTplParams, m.BaseRequestBuilder.RequestAdapter)
}
// NewVideosRequestBuilderInternal instantiates a new VideosRequestBuilder and sets the default values.
func NewVideosRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*VideosRequestBuilder) {
    m := &VideosRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/videos{?limit*,offset*,order*,sort*}", pathParameters),
    }
    return m
}
// NewVideosRequestBuilder instantiates a new VideosRequestBuilder and sets the default values.
func NewVideosRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*VideosRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewVideosRequestBuilderInternal(urlParams, requestAdapter)
}
// Get retrieve all videos for a specific project, with pagination and sorting.
// returns a PaginatedResponseVideoable when successful
// returns a ErrorResponse error when the service returns a 400 status code
// returns a ErrorResponse error when the service returns a 401 status code
// returns a ErrorResponse error when the service returns a 403 status code
// returns a ErrorResponse error when the service returns a 500 status code
func (m *VideosRequestBuilder) Get(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[VideosRequestBuilderGetQueryParameters])(if5fe6ebdb5303685c58216888d4b27c57bfc171364b5f0d7459d0af798f20bbf.PaginatedResponseVideoable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "400": i90c0e1ee53825fe36252e17a45e5d3b5f64ca0be4b2c3a2284950d3439c0ff4d.CreateErrorResponseFromDiscriminatorValue,
        "401": i90c0e1ee53825fe36252e17a45e5d3b5f64ca0be4b2c3a2284950d3439c0ff4d.CreateErrorResponseFromDiscriminatorValue,
        "403": i90c0e1ee53825fe36252e17a45e5d3b5f64ca0be4b2c3a2284950d3439c0ff4d.CreateErrorResponseFromDiscriminatorValue,
        "500": i90c0e1ee53825fe36252e17a45e5d3b5f64ca0be4b2c3a2284950d3439c0ff4d.CreateErrorResponseFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, if5fe6ebdb5303685c58216888d4b27c57bfc171364b5f0d7459d0af798f20bbf.CreatePaginatedResponseVideoFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(if5fe6ebdb5303685c58216888d4b27c57bfc171364b5f0d7459d0af798f20bbf.PaginatedResponseVideoable), nil
}
// Languages the languages property
// returns a *LanguagesRequestBuilder when successful
func (m *VideosRequestBuilder) Languages()(*LanguagesRequestBuilder) {
    return NewLanguagesRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// ToGetRequestInformation retrieve all videos for a specific project, with pagination and sorting.
// returns a *RequestInformation when successful
func (m *VideosRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[VideosRequestBuilderGetQueryParameters])(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ConfigureRequestInformation(requestInfo, requestConfiguration)
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// Upload the upload property
// returns a *UploadRequestBuilder when successful
func (m *VideosRequestBuilder) Upload()(*UploadRequestBuilder) {
    return NewUploadRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *VideosRequestBuilder when successful
func (m *VideosRequestBuilder) WithUrl(rawUrl string)(*VideosRequestBuilder) {
    return NewVideosRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
