/*
RIXL API

**Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.

API version: 2.0
Contact: support@rixl.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rixl

import (
	"encoding/json"
)

// checks if the GithubComQeeqezApiInternalVideosVideoResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GithubComQeeqezApiInternalVideosVideoResponse{}

// GithubComQeeqezApiInternalVideosVideoResponse struct for GithubComQeeqezApiInternalVideosVideoResponse
type GithubComQeeqezApiInternalVideosVideoResponse struct {
	Bitrate *int32 `json:"bitrate,omitempty"`
	Chapters []Chapter `json:"chapters,omitempty"`
	Codec *string `json:"codec,omitempty"`
	Duration *float32 `json:"duration,omitempty"`
	File *File `json:"file,omitempty"`
	Framerate *string `json:"framerate,omitempty"`
	Hdr *bool `json:"hdr,omitempty"`
	Height *int32 `json:"height,omitempty"`
	Id *string `json:"id,omitempty"`
	PlanType *GithubComQeeqezApiDbSqlcPlanType `json:"plan_type,omitempty"`
	Poster *Image `json:"poster,omitempty"`
	Width *int32 `json:"width,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GithubComQeeqezApiInternalVideosVideoResponse GithubComQeeqezApiInternalVideosVideoResponse

// NewGithubComQeeqezApiInternalVideosVideoResponse instantiates a new GithubComQeeqezApiInternalVideosVideoResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGithubComQeeqezApiInternalVideosVideoResponse() *GithubComQeeqezApiInternalVideosVideoResponse {
	this := GithubComQeeqezApiInternalVideosVideoResponse{}
	return &this
}

// NewGithubComQeeqezApiInternalVideosVideoResponseWithDefaults instantiates a new GithubComQeeqezApiInternalVideosVideoResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGithubComQeeqezApiInternalVideosVideoResponseWithDefaults() *GithubComQeeqezApiInternalVideosVideoResponse {
	this := GithubComQeeqezApiInternalVideosVideoResponse{}
	return &this
}

// GetBitrate returns the Bitrate field value if set, zero value otherwise.
func (o *GithubComQeeqezApiInternalVideosVideoResponse) GetBitrate() int32 {
	if o == nil || IsNil(o.Bitrate) {
		var ret int32
		return ret
	}
	return *o.Bitrate
}

// GetBitrateOk returns a tuple with the Bitrate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GithubComQeeqezApiInternalVideosVideoResponse) GetBitrateOk() (*int32, bool) {
	if o == nil || IsNil(o.Bitrate) {
		return nil, false
	}
	return o.Bitrate, true
}

// HasBitrate returns a boolean if a field has been set.
func (o *GithubComQeeqezApiInternalVideosVideoResponse) HasBitrate() bool {
	if o != nil && !IsNil(o.Bitrate) {
		return true
	}

	return false
}

// SetBitrate gets a reference to the given int32 and assigns it to the Bitrate field.
func (o *GithubComQeeqezApiInternalVideosVideoResponse) SetBitrate(v int32) {
	o.Bitrate = &v
}

// GetChapters returns the Chapters field value if set, zero value otherwise.
func (o *GithubComQeeqezApiInternalVideosVideoResponse) GetChapters() []Chapter {
	if o == nil || IsNil(o.Chapters) {
		var ret []Chapter
		return ret
	}
	return o.Chapters
}

// GetChaptersOk returns a tuple with the Chapters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GithubComQeeqezApiInternalVideosVideoResponse) GetChaptersOk() ([]Chapter, bool) {
	if o == nil || IsNil(o.Chapters) {
		return nil, false
	}
	return o.Chapters, true
}

// HasChapters returns a boolean if a field has been set.
func (o *GithubComQeeqezApiInternalVideosVideoResponse) HasChapters() bool {
	if o != nil && !IsNil(o.Chapters) {
		return true
	}

	return false
}

// SetChapters gets a reference to the given []Chapter and assigns it to the Chapters field.
func (o *GithubComQeeqezApiInternalVideosVideoResponse) SetChapters(v []Chapter) {
	o.Chapters = v
}

// GetCodec returns the Codec field value if set, zero value otherwise.
func (o *GithubComQeeqezApiInternalVideosVideoResponse) GetCodec() string {
	if o == nil || IsNil(o.Codec) {
		var ret string
		return ret
	}
	return *o.Codec
}

// GetCodecOk returns a tuple with the Codec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GithubComQeeqezApiInternalVideosVideoResponse) GetCodecOk() (*string, bool) {
	if o == nil || IsNil(o.Codec) {
		return nil, false
	}
	return o.Codec, true
}

// HasCodec returns a boolean if a field has been set.
func (o *GithubComQeeqezApiInternalVideosVideoResponse) HasCodec() bool {
	if o != nil && !IsNil(o.Codec) {
		return true
	}

	return false
}

// SetCodec gets a reference to the given string and assigns it to the Codec field.
func (o *GithubComQeeqezApiInternalVideosVideoResponse) SetCodec(v string) {
	o.Codec = &v
}

// GetDuration returns the Duration field value if set, zero value otherwise.
func (o *GithubComQeeqezApiInternalVideosVideoResponse) GetDuration() float32 {
	if o == nil || IsNil(o.Duration) {
		var ret float32
		return ret
	}
	return *o.Duration
}

// GetDurationOk returns a tuple with the Duration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GithubComQeeqezApiInternalVideosVideoResponse) GetDurationOk() (*float32, bool) {
	if o == nil || IsNil(o.Duration) {
		return nil, false
	}
	return o.Duration, true
}

// HasDuration returns a boolean if a field has been set.
func (o *GithubComQeeqezApiInternalVideosVideoResponse) HasDuration() bool {
	if o != nil && !IsNil(o.Duration) {
		return true
	}

	return false
}

// SetDuration gets a reference to the given float32 and assigns it to the Duration field.
func (o *GithubComQeeqezApiInternalVideosVideoResponse) SetDuration(v float32) {
	o.Duration = &v
}

// GetFile returns the File field value if set, zero value otherwise.
func (o *GithubComQeeqezApiInternalVideosVideoResponse) GetFile() File {
	if o == nil || IsNil(o.File) {
		var ret File
		return ret
	}
	return *o.File
}

// GetFileOk returns a tuple with the File field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GithubComQeeqezApiInternalVideosVideoResponse) GetFileOk() (*File, bool) {
	if o == nil || IsNil(o.File) {
		return nil, false
	}
	return o.File, true
}

// HasFile returns a boolean if a field has been set.
func (o *GithubComQeeqezApiInternalVideosVideoResponse) HasFile() bool {
	if o != nil && !IsNil(o.File) {
		return true
	}

	return false
}

// SetFile gets a reference to the given File and assigns it to the File field.
func (o *GithubComQeeqezApiInternalVideosVideoResponse) SetFile(v File) {
	o.File = &v
}

// GetFramerate returns the Framerate field value if set, zero value otherwise.
func (o *GithubComQeeqezApiInternalVideosVideoResponse) GetFramerate() string {
	if o == nil || IsNil(o.Framerate) {
		var ret string
		return ret
	}
	return *o.Framerate
}

// GetFramerateOk returns a tuple with the Framerate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GithubComQeeqezApiInternalVideosVideoResponse) GetFramerateOk() (*string, bool) {
	if o == nil || IsNil(o.Framerate) {
		return nil, false
	}
	return o.Framerate, true
}

// HasFramerate returns a boolean if a field has been set.
func (o *GithubComQeeqezApiInternalVideosVideoResponse) HasFramerate() bool {
	if o != nil && !IsNil(o.Framerate) {
		return true
	}

	return false
}

// SetFramerate gets a reference to the given string and assigns it to the Framerate field.
func (o *GithubComQeeqezApiInternalVideosVideoResponse) SetFramerate(v string) {
	o.Framerate = &v
}

// GetHdr returns the Hdr field value if set, zero value otherwise.
func (o *GithubComQeeqezApiInternalVideosVideoResponse) GetHdr() bool {
	if o == nil || IsNil(o.Hdr) {
		var ret bool
		return ret
	}
	return *o.Hdr
}

// GetHdrOk returns a tuple with the Hdr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GithubComQeeqezApiInternalVideosVideoResponse) GetHdrOk() (*bool, bool) {
	if o == nil || IsNil(o.Hdr) {
		return nil, false
	}
	return o.Hdr, true
}

// HasHdr returns a boolean if a field has been set.
func (o *GithubComQeeqezApiInternalVideosVideoResponse) HasHdr() bool {
	if o != nil && !IsNil(o.Hdr) {
		return true
	}

	return false
}

// SetHdr gets a reference to the given bool and assigns it to the Hdr field.
func (o *GithubComQeeqezApiInternalVideosVideoResponse) SetHdr(v bool) {
	o.Hdr = &v
}

// GetHeight returns the Height field value if set, zero value otherwise.
func (o *GithubComQeeqezApiInternalVideosVideoResponse) GetHeight() int32 {
	if o == nil || IsNil(o.Height) {
		var ret int32
		return ret
	}
	return *o.Height
}

// GetHeightOk returns a tuple with the Height field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GithubComQeeqezApiInternalVideosVideoResponse) GetHeightOk() (*int32, bool) {
	if o == nil || IsNil(o.Height) {
		return nil, false
	}
	return o.Height, true
}

// HasHeight returns a boolean if a field has been set.
func (o *GithubComQeeqezApiInternalVideosVideoResponse) HasHeight() bool {
	if o != nil && !IsNil(o.Height) {
		return true
	}

	return false
}

// SetHeight gets a reference to the given int32 and assigns it to the Height field.
func (o *GithubComQeeqezApiInternalVideosVideoResponse) SetHeight(v int32) {
	o.Height = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GithubComQeeqezApiInternalVideosVideoResponse) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GithubComQeeqezApiInternalVideosVideoResponse) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GithubComQeeqezApiInternalVideosVideoResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *GithubComQeeqezApiInternalVideosVideoResponse) SetId(v string) {
	o.Id = &v
}

// GetPlanType returns the PlanType field value if set, zero value otherwise.
func (o *GithubComQeeqezApiInternalVideosVideoResponse) GetPlanType() GithubComQeeqezApiDbSqlcPlanType {
	if o == nil || IsNil(o.PlanType) {
		var ret GithubComQeeqezApiDbSqlcPlanType
		return ret
	}
	return *o.PlanType
}

// GetPlanTypeOk returns a tuple with the PlanType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GithubComQeeqezApiInternalVideosVideoResponse) GetPlanTypeOk() (*GithubComQeeqezApiDbSqlcPlanType, bool) {
	if o == nil || IsNil(o.PlanType) {
		return nil, false
	}
	return o.PlanType, true
}

// HasPlanType returns a boolean if a field has been set.
func (o *GithubComQeeqezApiInternalVideosVideoResponse) HasPlanType() bool {
	if o != nil && !IsNil(o.PlanType) {
		return true
	}

	return false
}

// SetPlanType gets a reference to the given GithubComQeeqezApiDbSqlcPlanType and assigns it to the PlanType field.
func (o *GithubComQeeqezApiInternalVideosVideoResponse) SetPlanType(v GithubComQeeqezApiDbSqlcPlanType) {
	o.PlanType = &v
}

// GetPoster returns the Poster field value if set, zero value otherwise.
func (o *GithubComQeeqezApiInternalVideosVideoResponse) GetPoster() Image {
	if o == nil || IsNil(o.Poster) {
		var ret Image
		return ret
	}
	return *o.Poster
}

// GetPosterOk returns a tuple with the Poster field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GithubComQeeqezApiInternalVideosVideoResponse) GetPosterOk() (*Image, bool) {
	if o == nil || IsNil(o.Poster) {
		return nil, false
	}
	return o.Poster, true
}

// HasPoster returns a boolean if a field has been set.
func (o *GithubComQeeqezApiInternalVideosVideoResponse) HasPoster() bool {
	if o != nil && !IsNil(o.Poster) {
		return true
	}

	return false
}

// SetPoster gets a reference to the given Image and assigns it to the Poster field.
func (o *GithubComQeeqezApiInternalVideosVideoResponse) SetPoster(v Image) {
	o.Poster = &v
}

// GetWidth returns the Width field value if set, zero value otherwise.
func (o *GithubComQeeqezApiInternalVideosVideoResponse) GetWidth() int32 {
	if o == nil || IsNil(o.Width) {
		var ret int32
		return ret
	}
	return *o.Width
}

// GetWidthOk returns a tuple with the Width field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GithubComQeeqezApiInternalVideosVideoResponse) GetWidthOk() (*int32, bool) {
	if o == nil || IsNil(o.Width) {
		return nil, false
	}
	return o.Width, true
}

// HasWidth returns a boolean if a field has been set.
func (o *GithubComQeeqezApiInternalVideosVideoResponse) HasWidth() bool {
	if o != nil && !IsNil(o.Width) {
		return true
	}

	return false
}

// SetWidth gets a reference to the given int32 and assigns it to the Width field.
func (o *GithubComQeeqezApiInternalVideosVideoResponse) SetWidth(v int32) {
	o.Width = &v
}

func (o GithubComQeeqezApiInternalVideosVideoResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GithubComQeeqezApiInternalVideosVideoResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Bitrate) {
		toSerialize["bitrate"] = o.Bitrate
	}
	if !IsNil(o.Chapters) {
		toSerialize["chapters"] = o.Chapters
	}
	if !IsNil(o.Codec) {
		toSerialize["codec"] = o.Codec
	}
	if !IsNil(o.Duration) {
		toSerialize["duration"] = o.Duration
	}
	if !IsNil(o.File) {
		toSerialize["file"] = o.File
	}
	if !IsNil(o.Framerate) {
		toSerialize["framerate"] = o.Framerate
	}
	if !IsNil(o.Hdr) {
		toSerialize["hdr"] = o.Hdr
	}
	if !IsNil(o.Height) {
		toSerialize["height"] = o.Height
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.PlanType) {
		toSerialize["plan_type"] = o.PlanType
	}
	if !IsNil(o.Poster) {
		toSerialize["poster"] = o.Poster
	}
	if !IsNil(o.Width) {
		toSerialize["width"] = o.Width
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GithubComQeeqezApiInternalVideosVideoResponse) UnmarshalJSON(data []byte) (err error) {
	varGithubComQeeqezApiInternalVideosVideoResponse := _GithubComQeeqezApiInternalVideosVideoResponse{}

	err = json.Unmarshal(data, &varGithubComQeeqezApiInternalVideosVideoResponse)

	if err != nil {
		return err
	}

	*o = GithubComQeeqezApiInternalVideosVideoResponse(varGithubComQeeqezApiInternalVideosVideoResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "bitrate")
		delete(additionalProperties, "chapters")
		delete(additionalProperties, "codec")
		delete(additionalProperties, "duration")
		delete(additionalProperties, "file")
		delete(additionalProperties, "framerate")
		delete(additionalProperties, "hdr")
		delete(additionalProperties, "height")
		delete(additionalProperties, "id")
		delete(additionalProperties, "plan_type")
		delete(additionalProperties, "poster")
		delete(additionalProperties, "width")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGithubComQeeqezApiInternalVideosVideoResponse struct {
	value *GithubComQeeqezApiInternalVideosVideoResponse
	isSet bool
}

func (v NullableGithubComQeeqezApiInternalVideosVideoResponse) Get() *GithubComQeeqezApiInternalVideosVideoResponse {
	return v.value
}

func (v *NullableGithubComQeeqezApiInternalVideosVideoResponse) Set(val *GithubComQeeqezApiInternalVideosVideoResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGithubComQeeqezApiInternalVideosVideoResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGithubComQeeqezApiInternalVideosVideoResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGithubComQeeqezApiInternalVideosVideoResponse(val *GithubComQeeqezApiInternalVideosVideoResponse) *NullableGithubComQeeqezApiInternalVideosVideoResponse {
	return &NullableGithubComQeeqezApiInternalVideosVideoResponse{value: val, isSet: true}
}

func (v NullableGithubComQeeqezApiInternalVideosVideoResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGithubComQeeqezApiInternalVideosVideoResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


