/*
RIXL API

**Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.

API version: 2.0
Contact: support@rixl.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rixl

import (
	"encoding/json"
)

// checks if the PaginationPaginatedResponseImage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginationPaginatedResponseImage{}

// PaginationPaginatedResponseImage struct for PaginationPaginatedResponseImage
type PaginationPaginatedResponseImage struct {
	// Data contains the slice of items for the current request.
	Data []Image `json:"data,omitempty"`
	// Pagination data for the request.
	Pagination *PaginationPagination `json:"pagination,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PaginationPaginatedResponseImage PaginationPaginatedResponseImage

// NewPaginationPaginatedResponseImage instantiates a new PaginationPaginatedResponseImage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginationPaginatedResponseImage() *PaginationPaginatedResponseImage {
	this := PaginationPaginatedResponseImage{}
	return &this
}

// NewPaginationPaginatedResponseImageWithDefaults instantiates a new PaginationPaginatedResponseImage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginationPaginatedResponseImageWithDefaults() *PaginationPaginatedResponseImage {
	this := PaginationPaginatedResponseImage{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *PaginationPaginatedResponseImage) GetData() []Image {
	if o == nil || IsNil(o.Data) {
		var ret []Image
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginationPaginatedResponseImage) GetDataOk() ([]Image, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *PaginationPaginatedResponseImage) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []Image and assigns it to the Data field.
func (o *PaginationPaginatedResponseImage) SetData(v []Image) {
	o.Data = v
}

// GetPagination returns the Pagination field value if set, zero value otherwise.
func (o *PaginationPaginatedResponseImage) GetPagination() PaginationPagination {
	if o == nil || IsNil(o.Pagination) {
		var ret PaginationPagination
		return ret
	}
	return *o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginationPaginatedResponseImage) GetPaginationOk() (*PaginationPagination, bool) {
	if o == nil || IsNil(o.Pagination) {
		return nil, false
	}
	return o.Pagination, true
}

// HasPagination returns a boolean if a field has been set.
func (o *PaginationPaginatedResponseImage) HasPagination() bool {
	if o != nil && !IsNil(o.Pagination) {
		return true
	}

	return false
}

// SetPagination gets a reference to the given PaginationPagination and assigns it to the Pagination field.
func (o *PaginationPaginatedResponseImage) SetPagination(v PaginationPagination) {
	o.Pagination = &v
}

func (o PaginationPaginatedResponseImage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginationPaginatedResponseImage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Pagination) {
		toSerialize["pagination"] = o.Pagination
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PaginationPaginatedResponseImage) UnmarshalJSON(data []byte) (err error) {
	varPaginationPaginatedResponseImage := _PaginationPaginatedResponseImage{}

	err = json.Unmarshal(data, &varPaginationPaginatedResponseImage)

	if err != nil {
		return err
	}

	*o = PaginationPaginatedResponseImage(varPaginationPaginatedResponseImage)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		delete(additionalProperties, "pagination")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePaginationPaginatedResponseImage struct {
	value *PaginationPaginatedResponseImage
	isSet bool
}

func (v NullablePaginationPaginatedResponseImage) Get() *PaginationPaginatedResponseImage {
	return v.value
}

func (v *NullablePaginationPaginatedResponseImage) Set(val *PaginationPaginatedResponseImage) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginationPaginatedResponseImage) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginationPaginatedResponseImage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginationPaginatedResponseImage(val *PaginationPaginatedResponseImage) *NullablePaginationPaginatedResponseImage {
	return &NullablePaginationPaginatedResponseImage{value: val, isSet: true}
}

func (v NullablePaginationPaginatedResponseImage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginationPaginatedResponseImage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


