/*
RIXL API

**Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.

API version: 2.0
Contact: support@rixl.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rixl

import (
	"encoding/json"
	"fmt"
)

// GithubComQeeqezApiDbSqlcPlanType the model 'GithubComQeeqezApiDbSqlcPlanType'
type GithubComQeeqezApiDbSqlcPlanType string

// List of github_com_qeeqez_api_db_sqlc.PlanType
const (
	GITHUBCOMQEEQEZAPIDBSQLCPLANTYPE_PlanTypeFree GithubComQeeqezApiDbSqlcPlanType = "free"
	GITHUBCOMQEEQEZAPIDBSQLCPLANTYPE_PlanTypePro GithubComQeeqezApiDbSqlcPlanType = "pro"
	GITHUBCOMQEEQEZAPIDBSQLCPLANTYPE_PlanTypeCustom GithubComQeeqezApiDbSqlcPlanType = "custom"
	GITHUBCOMQEEQEZAPIDBSQLCPLANTYPE_PlanTypePayAsYouGo GithubComQeeqezApiDbSqlcPlanType = "pay_as_you_go"
)

// All allowed values of GithubComQeeqezApiDbSqlcPlanType enum
var AllowedGithubComQeeqezApiDbSqlcPlanTypeEnumValues = []GithubComQeeqezApiDbSqlcPlanType{
	"free",
	"pro",
	"custom",
	"pay_as_you_go",
}

func (v *GithubComQeeqezApiDbSqlcPlanType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := GithubComQeeqezApiDbSqlcPlanType(value)
	for _, existing := range AllowedGithubComQeeqezApiDbSqlcPlanTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid GithubComQeeqezApiDbSqlcPlanType", value)
}

// NewGithubComQeeqezApiDbSqlcPlanTypeFromValue returns a pointer to a valid GithubComQeeqezApiDbSqlcPlanType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewGithubComQeeqezApiDbSqlcPlanTypeFromValue(v string) (*GithubComQeeqezApiDbSqlcPlanType, error) {
	ev := GithubComQeeqezApiDbSqlcPlanType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for GithubComQeeqezApiDbSqlcPlanType: valid values are %v", v, AllowedGithubComQeeqezApiDbSqlcPlanTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v GithubComQeeqezApiDbSqlcPlanType) IsValid() bool {
	for _, existing := range AllowedGithubComQeeqezApiDbSqlcPlanTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to github_com_qeeqez_api_db_sqlc.PlanType value
func (v GithubComQeeqezApiDbSqlcPlanType) Ptr() *GithubComQeeqezApiDbSqlcPlanType {
	return &v
}

type NullableGithubComQeeqezApiDbSqlcPlanType struct {
	value *GithubComQeeqezApiDbSqlcPlanType
	isSet bool
}

func (v NullableGithubComQeeqezApiDbSqlcPlanType) Get() *GithubComQeeqezApiDbSqlcPlanType {
	return v.value
}

func (v *NullableGithubComQeeqezApiDbSqlcPlanType) Set(val *GithubComQeeqezApiDbSqlcPlanType) {
	v.value = val
	v.isSet = true
}

func (v NullableGithubComQeeqezApiDbSqlcPlanType) IsSet() bool {
	return v.isSet
}

func (v *NullableGithubComQeeqezApiDbSqlcPlanType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGithubComQeeqezApiDbSqlcPlanType(val *GithubComQeeqezApiDbSqlcPlanType) *NullableGithubComQeeqezApiDbSqlcPlanType {
	return &NullableGithubComQeeqezApiDbSqlcPlanType{value: val, isSet: true}
}

func (v NullableGithubComQeeqezApiDbSqlcPlanType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGithubComQeeqezApiDbSqlcPlanType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

