/*
RIXL API

**Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.

API version: 2.0
Contact: support@rixl.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rixl

import (
	"encoding/json"
)

// checks if the GithubComQeeqezApiInternalVideosTypesChapterInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GithubComQeeqezApiInternalVideosTypesChapterInput{}

// GithubComQeeqezApiInternalVideosTypesChapterInput struct for GithubComQeeqezApiInternalVideosTypesChapterInput
type GithubComQeeqezApiInternalVideosTypesChapterInput struct {
	StartTimeSec *float32 `json:"start_time_sec,omitempty"`
	Title *string `json:"title,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GithubComQeeqezApiInternalVideosTypesChapterInput GithubComQeeqezApiInternalVideosTypesChapterInput

// NewGithubComQeeqezApiInternalVideosTypesChapterInput instantiates a new GithubComQeeqezApiInternalVideosTypesChapterInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGithubComQeeqezApiInternalVideosTypesChapterInput() *GithubComQeeqezApiInternalVideosTypesChapterInput {
	this := GithubComQeeqezApiInternalVideosTypesChapterInput{}
	return &this
}

// NewGithubComQeeqezApiInternalVideosTypesChapterInputWithDefaults instantiates a new GithubComQeeqezApiInternalVideosTypesChapterInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGithubComQeeqezApiInternalVideosTypesChapterInputWithDefaults() *GithubComQeeqezApiInternalVideosTypesChapterInput {
	this := GithubComQeeqezApiInternalVideosTypesChapterInput{}
	return &this
}

// GetStartTimeSec returns the StartTimeSec field value if set, zero value otherwise.
func (o *GithubComQeeqezApiInternalVideosTypesChapterInput) GetStartTimeSec() float32 {
	if o == nil || IsNil(o.StartTimeSec) {
		var ret float32
		return ret
	}
	return *o.StartTimeSec
}

// GetStartTimeSecOk returns a tuple with the StartTimeSec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GithubComQeeqezApiInternalVideosTypesChapterInput) GetStartTimeSecOk() (*float32, bool) {
	if o == nil || IsNil(o.StartTimeSec) {
		return nil, false
	}
	return o.StartTimeSec, true
}

// HasStartTimeSec returns a boolean if a field has been set.
func (o *GithubComQeeqezApiInternalVideosTypesChapterInput) HasStartTimeSec() bool {
	if o != nil && !IsNil(o.StartTimeSec) {
		return true
	}

	return false
}

// SetStartTimeSec gets a reference to the given float32 and assigns it to the StartTimeSec field.
func (o *GithubComQeeqezApiInternalVideosTypesChapterInput) SetStartTimeSec(v float32) {
	o.StartTimeSec = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *GithubComQeeqezApiInternalVideosTypesChapterInput) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GithubComQeeqezApiInternalVideosTypesChapterInput) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *GithubComQeeqezApiInternalVideosTypesChapterInput) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *GithubComQeeqezApiInternalVideosTypesChapterInput) SetTitle(v string) {
	o.Title = &v
}

func (o GithubComQeeqezApiInternalVideosTypesChapterInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GithubComQeeqezApiInternalVideosTypesChapterInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.StartTimeSec) {
		toSerialize["start_time_sec"] = o.StartTimeSec
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GithubComQeeqezApiInternalVideosTypesChapterInput) UnmarshalJSON(data []byte) (err error) {
	varGithubComQeeqezApiInternalVideosTypesChapterInput := _GithubComQeeqezApiInternalVideosTypesChapterInput{}

	err = json.Unmarshal(data, &varGithubComQeeqezApiInternalVideosTypesChapterInput)

	if err != nil {
		return err
	}

	*o = GithubComQeeqezApiInternalVideosTypesChapterInput(varGithubComQeeqezApiInternalVideosTypesChapterInput)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "start_time_sec")
		delete(additionalProperties, "title")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGithubComQeeqezApiInternalVideosTypesChapterInput struct {
	value *GithubComQeeqezApiInternalVideosTypesChapterInput
	isSet bool
}

func (v NullableGithubComQeeqezApiInternalVideosTypesChapterInput) Get() *GithubComQeeqezApiInternalVideosTypesChapterInput {
	return v.value
}

func (v *NullableGithubComQeeqezApiInternalVideosTypesChapterInput) Set(val *GithubComQeeqezApiInternalVideosTypesChapterInput) {
	v.value = val
	v.isSet = true
}

func (v NullableGithubComQeeqezApiInternalVideosTypesChapterInput) IsSet() bool {
	return v.isSet
}

func (v *NullableGithubComQeeqezApiInternalVideosTypesChapterInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGithubComQeeqezApiInternalVideosTypesChapterInput(val *GithubComQeeqezApiInternalVideosTypesChapterInput) *NullableGithubComQeeqezApiInternalVideosTypesChapterInput {
	return &NullableGithubComQeeqezApiInternalVideosTypesChapterInput{value: val, isSet: true}
}

func (v NullableGithubComQeeqezApiInternalVideosTypesChapterInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGithubComQeeqezApiInternalVideosTypesChapterInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


