/*
RIXL API

**Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.

API version: 2.0
Contact: support@rixl.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rixl

import (
	"encoding/json"
	"fmt"
)

// checks if the VideoUploadInitRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VideoUploadInitRequest{}

// VideoUploadInitRequest struct for VideoUploadInitRequest
type VideoUploadInitRequest struct {
	FileName string `json:"file_name"`
	ImageFormat *string `json:"image_format,omitempty"`
	VideoQuality *GithubComQeeqezApiDbSqlcVideoQuality `json:"video_quality,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _VideoUploadInitRequest VideoUploadInitRequest

// NewVideoUploadInitRequest instantiates a new VideoUploadInitRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVideoUploadInitRequest(fileName string) *VideoUploadInitRequest {
	this := VideoUploadInitRequest{}
	this.FileName = fileName
	return &this
}

// NewVideoUploadInitRequestWithDefaults instantiates a new VideoUploadInitRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVideoUploadInitRequestWithDefaults() *VideoUploadInitRequest {
	this := VideoUploadInitRequest{}
	return &this
}

// GetFileName returns the FileName field value
func (o *VideoUploadInitRequest) GetFileName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FileName
}

// GetFileNameOk returns a tuple with the FileName field value
// and a boolean to check if the value has been set.
func (o *VideoUploadInitRequest) GetFileNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FileName, true
}

// SetFileName sets field value
func (o *VideoUploadInitRequest) SetFileName(v string) {
	o.FileName = v
}

// GetImageFormat returns the ImageFormat field value if set, zero value otherwise.
func (o *VideoUploadInitRequest) GetImageFormat() string {
	if o == nil || IsNil(o.ImageFormat) {
		var ret string
		return ret
	}
	return *o.ImageFormat
}

// GetImageFormatOk returns a tuple with the ImageFormat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoUploadInitRequest) GetImageFormatOk() (*string, bool) {
	if o == nil || IsNil(o.ImageFormat) {
		return nil, false
	}
	return o.ImageFormat, true
}

// HasImageFormat returns a boolean if a field has been set.
func (o *VideoUploadInitRequest) HasImageFormat() bool {
	if o != nil && !IsNil(o.ImageFormat) {
		return true
	}

	return false
}

// SetImageFormat gets a reference to the given string and assigns it to the ImageFormat field.
func (o *VideoUploadInitRequest) SetImageFormat(v string) {
	o.ImageFormat = &v
}

// GetVideoQuality returns the VideoQuality field value if set, zero value otherwise.
func (o *VideoUploadInitRequest) GetVideoQuality() GithubComQeeqezApiDbSqlcVideoQuality {
	if o == nil || IsNil(o.VideoQuality) {
		var ret GithubComQeeqezApiDbSqlcVideoQuality
		return ret
	}
	return *o.VideoQuality
}

// GetVideoQualityOk returns a tuple with the VideoQuality field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoUploadInitRequest) GetVideoQualityOk() (*GithubComQeeqezApiDbSqlcVideoQuality, bool) {
	if o == nil || IsNil(o.VideoQuality) {
		return nil, false
	}
	return o.VideoQuality, true
}

// HasVideoQuality returns a boolean if a field has been set.
func (o *VideoUploadInitRequest) HasVideoQuality() bool {
	if o != nil && !IsNil(o.VideoQuality) {
		return true
	}

	return false
}

// SetVideoQuality gets a reference to the given GithubComQeeqezApiDbSqlcVideoQuality and assigns it to the VideoQuality field.
func (o *VideoUploadInitRequest) SetVideoQuality(v GithubComQeeqezApiDbSqlcVideoQuality) {
	o.VideoQuality = &v
}

func (o VideoUploadInitRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VideoUploadInitRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["file_name"] = o.FileName
	if !IsNil(o.ImageFormat) {
		toSerialize["image_format"] = o.ImageFormat
	}
	if !IsNil(o.VideoQuality) {
		toSerialize["video_quality"] = o.VideoQuality
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *VideoUploadInitRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"file_name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVideoUploadInitRequest := _VideoUploadInitRequest{}

	err = json.Unmarshal(data, &varVideoUploadInitRequest)

	if err != nil {
		return err
	}

	*o = VideoUploadInitRequest(varVideoUploadInitRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "file_name")
		delete(additionalProperties, "image_format")
		delete(additionalProperties, "video_quality")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableVideoUploadInitRequest struct {
	value *VideoUploadInitRequest
	isSet bool
}

func (v NullableVideoUploadInitRequest) Get() *VideoUploadInitRequest {
	return v.value
}

func (v *NullableVideoUploadInitRequest) Set(val *VideoUploadInitRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableVideoUploadInitRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableVideoUploadInitRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVideoUploadInitRequest(val *VideoUploadInitRequest) *NullableVideoUploadInitRequest {
	return &NullableVideoUploadInitRequest{value: val, isSet: true}
}

func (v NullableVideoUploadInitRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVideoUploadInitRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


