/*
RIXL API

**Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.

API version: 2.0
Contact: support@rixl.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rixl

import (
	"encoding/json"
)

// checks if the PaginationPagination type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginationPagination{}

// PaginationPagination struct for PaginationPagination
type PaginationPagination struct {
	// Maximum number of items to return in a single request.
	Limit *int32 `json:"limit,omitempty"`
	// Starting point of the result set.
	Offset *int32 `json:"offset,omitempty"`
	// The total number of available items in the full list.
	Total *int32 `json:"total,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PaginationPagination PaginationPagination

// NewPaginationPagination instantiates a new PaginationPagination object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginationPagination() *PaginationPagination {
	this := PaginationPagination{}
	return &this
}

// NewPaginationPaginationWithDefaults instantiates a new PaginationPagination object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginationPaginationWithDefaults() *PaginationPagination {
	this := PaginationPagination{}
	return &this
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *PaginationPagination) GetLimit() int32 {
	if o == nil || IsNil(o.Limit) {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginationPagination) GetLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.Limit) {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *PaginationPagination) HasLimit() bool {
	if o != nil && !IsNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *PaginationPagination) SetLimit(v int32) {
	o.Limit = &v
}

// GetOffset returns the Offset field value if set, zero value otherwise.
func (o *PaginationPagination) GetOffset() int32 {
	if o == nil || IsNil(o.Offset) {
		var ret int32
		return ret
	}
	return *o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginationPagination) GetOffsetOk() (*int32, bool) {
	if o == nil || IsNil(o.Offset) {
		return nil, false
	}
	return o.Offset, true
}

// HasOffset returns a boolean if a field has been set.
func (o *PaginationPagination) HasOffset() bool {
	if o != nil && !IsNil(o.Offset) {
		return true
	}

	return false
}

// SetOffset gets a reference to the given int32 and assigns it to the Offset field.
func (o *PaginationPagination) SetOffset(v int32) {
	o.Offset = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *PaginationPagination) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginationPagination) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *PaginationPagination) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *PaginationPagination) SetTotal(v int32) {
	o.Total = &v
}

func (o PaginationPagination) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginationPagination) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Limit) {
		toSerialize["limit"] = o.Limit
	}
	if !IsNil(o.Offset) {
		toSerialize["offset"] = o.Offset
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PaginationPagination) UnmarshalJSON(data []byte) (err error) {
	varPaginationPagination := _PaginationPagination{}

	err = json.Unmarshal(data, &varPaginationPagination)

	if err != nil {
		return err
	}

	*o = PaginationPagination(varPaginationPagination)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "limit")
		delete(additionalProperties, "offset")
		delete(additionalProperties, "total")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePaginationPagination struct {
	value *PaginationPagination
	isSet bool
}

func (v NullablePaginationPagination) Get() *PaginationPagination {
	return v.value
}

func (v *NullablePaginationPagination) Set(val *PaginationPagination) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginationPagination) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginationPagination) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginationPagination(val *PaginationPagination) *NullablePaginationPagination {
	return &NullablePaginationPagination{value: val, isSet: true}
}

func (v NullablePaginationPagination) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginationPagination) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


