/*
RIXL API

**Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.

API version: 2.0
Contact: support@rixl.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rixl

import (
	"encoding/json"
)

// checks if the InternalImagesHandlerInitResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InternalImagesHandlerInitResponse{}

// InternalImagesHandlerInitResponse struct for InternalImagesHandlerInitResponse
type InternalImagesHandlerInitResponse struct {
	ImageId *string `json:"image_id,omitempty"`
	PresignedUrl *string `json:"presigned_url,omitempty"`
	UploadExpires *int32 `json:"upload_expires,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _InternalImagesHandlerInitResponse InternalImagesHandlerInitResponse

// NewInternalImagesHandlerInitResponse instantiates a new InternalImagesHandlerInitResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInternalImagesHandlerInitResponse() *InternalImagesHandlerInitResponse {
	this := InternalImagesHandlerInitResponse{}
	return &this
}

// NewInternalImagesHandlerInitResponseWithDefaults instantiates a new InternalImagesHandlerInitResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInternalImagesHandlerInitResponseWithDefaults() *InternalImagesHandlerInitResponse {
	this := InternalImagesHandlerInitResponse{}
	return &this
}

// GetImageId returns the ImageId field value if set, zero value otherwise.
func (o *InternalImagesHandlerInitResponse) GetImageId() string {
	if o == nil || IsNil(o.ImageId) {
		var ret string
		return ret
	}
	return *o.ImageId
}

// GetImageIdOk returns a tuple with the ImageId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternalImagesHandlerInitResponse) GetImageIdOk() (*string, bool) {
	if o == nil || IsNil(o.ImageId) {
		return nil, false
	}
	return o.ImageId, true
}

// HasImageId returns a boolean if a field has been set.
func (o *InternalImagesHandlerInitResponse) HasImageId() bool {
	if o != nil && !IsNil(o.ImageId) {
		return true
	}

	return false
}

// SetImageId gets a reference to the given string and assigns it to the ImageId field.
func (o *InternalImagesHandlerInitResponse) SetImageId(v string) {
	o.ImageId = &v
}

// GetPresignedUrl returns the PresignedUrl field value if set, zero value otherwise.
func (o *InternalImagesHandlerInitResponse) GetPresignedUrl() string {
	if o == nil || IsNil(o.PresignedUrl) {
		var ret string
		return ret
	}
	return *o.PresignedUrl
}

// GetPresignedUrlOk returns a tuple with the PresignedUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternalImagesHandlerInitResponse) GetPresignedUrlOk() (*string, bool) {
	if o == nil || IsNil(o.PresignedUrl) {
		return nil, false
	}
	return o.PresignedUrl, true
}

// HasPresignedUrl returns a boolean if a field has been set.
func (o *InternalImagesHandlerInitResponse) HasPresignedUrl() bool {
	if o != nil && !IsNil(o.PresignedUrl) {
		return true
	}

	return false
}

// SetPresignedUrl gets a reference to the given string and assigns it to the PresignedUrl field.
func (o *InternalImagesHandlerInitResponse) SetPresignedUrl(v string) {
	o.PresignedUrl = &v
}

// GetUploadExpires returns the UploadExpires field value if set, zero value otherwise.
func (o *InternalImagesHandlerInitResponse) GetUploadExpires() int32 {
	if o == nil || IsNil(o.UploadExpires) {
		var ret int32
		return ret
	}
	return *o.UploadExpires
}

// GetUploadExpiresOk returns a tuple with the UploadExpires field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternalImagesHandlerInitResponse) GetUploadExpiresOk() (*int32, bool) {
	if o == nil || IsNil(o.UploadExpires) {
		return nil, false
	}
	return o.UploadExpires, true
}

// HasUploadExpires returns a boolean if a field has been set.
func (o *InternalImagesHandlerInitResponse) HasUploadExpires() bool {
	if o != nil && !IsNil(o.UploadExpires) {
		return true
	}

	return false
}

// SetUploadExpires gets a reference to the given int32 and assigns it to the UploadExpires field.
func (o *InternalImagesHandlerInitResponse) SetUploadExpires(v int32) {
	o.UploadExpires = &v
}

func (o InternalImagesHandlerInitResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InternalImagesHandlerInitResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ImageId) {
		toSerialize["image_id"] = o.ImageId
	}
	if !IsNil(o.PresignedUrl) {
		toSerialize["presigned_url"] = o.PresignedUrl
	}
	if !IsNil(o.UploadExpires) {
		toSerialize["upload_expires"] = o.UploadExpires
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *InternalImagesHandlerInitResponse) UnmarshalJSON(data []byte) (err error) {
	varInternalImagesHandlerInitResponse := _InternalImagesHandlerInitResponse{}

	err = json.Unmarshal(data, &varInternalImagesHandlerInitResponse)

	if err != nil {
		return err
	}

	*o = InternalImagesHandlerInitResponse(varInternalImagesHandlerInitResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "image_id")
		delete(additionalProperties, "presigned_url")
		delete(additionalProperties, "upload_expires")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableInternalImagesHandlerInitResponse struct {
	value *InternalImagesHandlerInitResponse
	isSet bool
}

func (v NullableInternalImagesHandlerInitResponse) Get() *InternalImagesHandlerInitResponse {
	return v.value
}

func (v *NullableInternalImagesHandlerInitResponse) Set(val *InternalImagesHandlerInitResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableInternalImagesHandlerInitResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableInternalImagesHandlerInitResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInternalImagesHandlerInitResponse(val *InternalImagesHandlerInitResponse) *NullableInternalImagesHandlerInitResponse {
	return &NullableInternalImagesHandlerInitResponse{value: val, isSet: true}
}

func (v NullableInternalImagesHandlerInitResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInternalImagesHandlerInitResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


