/*
RIXL API

**Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.

API version: 2.0
Contact: support@rixl.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rixl

import (
	"encoding/json"
)

// checks if the SubtitleDelete type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubtitleDelete{}

// SubtitleDelete struct for SubtitleDelete
type SubtitleDelete struct {
	Message *string `json:"message,omitempty"`
	Status *string `json:"status,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SubtitleDelete SubtitleDelete

// NewSubtitleDelete instantiates a new SubtitleDelete object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubtitleDelete() *SubtitleDelete {
	this := SubtitleDelete{}
	return &this
}

// NewSubtitleDeleteWithDefaults instantiates a new SubtitleDelete object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubtitleDeleteWithDefaults() *SubtitleDelete {
	this := SubtitleDelete{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *SubtitleDelete) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubtitleDelete) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *SubtitleDelete) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *SubtitleDelete) SetMessage(v string) {
	o.Message = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *SubtitleDelete) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubtitleDelete) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *SubtitleDelete) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *SubtitleDelete) SetStatus(v string) {
	o.Status = &v
}

func (o SubtitleDelete) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubtitleDelete) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SubtitleDelete) UnmarshalJSON(data []byte) (err error) {
	varSubtitleDelete := _SubtitleDelete{}

	err = json.Unmarshal(data, &varSubtitleDelete)

	if err != nil {
		return err
	}

	*o = SubtitleDelete(varSubtitleDelete)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "message")
		delete(additionalProperties, "status")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSubtitleDelete struct {
	value *SubtitleDelete
	isSet bool
}

func (v NullableSubtitleDelete) Get() *SubtitleDelete {
	return v.value
}

func (v *NullableSubtitleDelete) Set(val *SubtitleDelete) {
	v.value = val
	v.isSet = true
}

func (v NullableSubtitleDelete) IsSet() bool {
	return v.isSet
}

func (v *NullableSubtitleDelete) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubtitleDelete(val *SubtitleDelete) *NullableSubtitleDelete {
	return &NullableSubtitleDelete{value: val, isSet: true}
}

func (v NullableSubtitleDelete) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubtitleDelete) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


