/*
RIXL API

**Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.

API version: 2.0
Contact: support@rixl.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rixl

import (
	"encoding/json"
)

// checks if the PaginationPaginatedResponsePost type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginationPaginatedResponsePost{}

// PaginationPaginatedResponsePost struct for PaginationPaginatedResponsePost
type PaginationPaginatedResponsePost struct {
	// Data contains the slice of items for the current request.
	Data []Post `json:"data,omitempty"`
	// Pagination data for the request.
	Pagination *PaginationPagination `json:"pagination,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PaginationPaginatedResponsePost PaginationPaginatedResponsePost

// NewPaginationPaginatedResponsePost instantiates a new PaginationPaginatedResponsePost object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginationPaginatedResponsePost() *PaginationPaginatedResponsePost {
	this := PaginationPaginatedResponsePost{}
	return &this
}

// NewPaginationPaginatedResponsePostWithDefaults instantiates a new PaginationPaginatedResponsePost object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginationPaginatedResponsePostWithDefaults() *PaginationPaginatedResponsePost {
	this := PaginationPaginatedResponsePost{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *PaginationPaginatedResponsePost) GetData() []Post {
	if o == nil || IsNil(o.Data) {
		var ret []Post
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginationPaginatedResponsePost) GetDataOk() ([]Post, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *PaginationPaginatedResponsePost) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []Post and assigns it to the Data field.
func (o *PaginationPaginatedResponsePost) SetData(v []Post) {
	o.Data = v
}

// GetPagination returns the Pagination field value if set, zero value otherwise.
func (o *PaginationPaginatedResponsePost) GetPagination() PaginationPagination {
	if o == nil || IsNil(o.Pagination) {
		var ret PaginationPagination
		return ret
	}
	return *o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginationPaginatedResponsePost) GetPaginationOk() (*PaginationPagination, bool) {
	if o == nil || IsNil(o.Pagination) {
		return nil, false
	}
	return o.Pagination, true
}

// HasPagination returns a boolean if a field has been set.
func (o *PaginationPaginatedResponsePost) HasPagination() bool {
	if o != nil && !IsNil(o.Pagination) {
		return true
	}

	return false
}

// SetPagination gets a reference to the given PaginationPagination and assigns it to the Pagination field.
func (o *PaginationPaginatedResponsePost) SetPagination(v PaginationPagination) {
	o.Pagination = &v
}

func (o PaginationPaginatedResponsePost) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginationPaginatedResponsePost) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Pagination) {
		toSerialize["pagination"] = o.Pagination
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PaginationPaginatedResponsePost) UnmarshalJSON(data []byte) (err error) {
	varPaginationPaginatedResponsePost := _PaginationPaginatedResponsePost{}

	err = json.Unmarshal(data, &varPaginationPaginatedResponsePost)

	if err != nil {
		return err
	}

	*o = PaginationPaginatedResponsePost(varPaginationPaginatedResponsePost)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		delete(additionalProperties, "pagination")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePaginationPaginatedResponsePost struct {
	value *PaginationPaginatedResponsePost
	isSet bool
}

func (v NullablePaginationPaginatedResponsePost) Get() *PaginationPaginatedResponsePost {
	return v.value
}

func (v *NullablePaginationPaginatedResponsePost) Set(val *PaginationPaginatedResponsePost) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginationPaginatedResponsePost) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginationPaginatedResponsePost) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginationPaginatedResponsePost(val *PaginationPaginatedResponsePost) *NullablePaginationPaginatedResponsePost {
	return &NullablePaginationPaginatedResponsePost{value: val, isSet: true}
}

func (v NullablePaginationPaginatedResponsePost) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginationPaginatedResponsePost) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


