/*
RIXL API

Testing VideosAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package videos

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_videos_VideosAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test VideosAPIService DeleteVideosVideoIdAudioTracks", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var videoId string

		resp, httpRes, err := apiClient.VideosAPI.DeleteVideosVideoIdAudioTracks(context.Background(), videoId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VideosAPIService DeleteVideosVideoIdAudioTracksLangCode", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var videoId string
		var langCode string

		resp, httpRes, err := apiClient.VideosAPI.DeleteVideosVideoIdAudioTracksLangCode(context.Background(), videoId, langCode).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VideosAPIService DeleteVideosVideoIdAudioTracksTrackId", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var videoId string
		var trackId string

		resp, httpRes, err := apiClient.VideosAPI.DeleteVideosVideoIdAudioTracksTrackId(context.Background(), videoId, trackId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VideosAPIService DeleteVideosVideoIdChapters", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var videoId string

		resp, httpRes, err := apiClient.VideosAPI.DeleteVideosVideoIdChapters(context.Background(), videoId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VideosAPIService DeleteVideosVideoIdDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var videoId string

		httpRes, err := apiClient.VideosAPI.DeleteVideosVideoIdDelete(context.Background(), videoId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VideosAPIService DeleteVideosVideoIdSubtitles", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var videoId string

		resp, httpRes, err := apiClient.VideosAPI.DeleteVideosVideoIdSubtitles(context.Background(), videoId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VideosAPIService DeleteVideosVideoIdSubtitlesLangCode", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var videoId string
		var langCode string

		resp, httpRes, err := apiClient.VideosAPI.DeleteVideosVideoIdSubtitlesLangCode(context.Background(), videoId, langCode).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VideosAPIService DeleteVideosVideoIdSubtitlesSubtitleId", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var videoId string
		var subtitleId string

		resp, httpRes, err := apiClient.VideosAPI.DeleteVideosVideoIdSubtitlesSubtitleId(context.Background(), videoId, subtitleId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VideosAPIService GetVideos", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.VideosAPI.GetVideos(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VideosAPIService GetVideosLanguages", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.VideosAPI.GetVideosLanguages(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VideosAPIService GetVideosVideoId", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var videoId string

		resp, httpRes, err := apiClient.VideosAPI.GetVideosVideoId(context.Background(), videoId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VideosAPIService PostVideosUploadComplete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.VideosAPI.PostVideosUploadComplete(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VideosAPIService PostVideosUploadInit", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.VideosAPI.PostVideosUploadInit(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VideosAPIService PostVideosVideoIdAudioTracks", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var videoId string

		resp, httpRes, err := apiClient.VideosAPI.PostVideosVideoIdAudioTracks(context.Background(), videoId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VideosAPIService PostVideosVideoIdSubtitles", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var videoId string

		resp, httpRes, err := apiClient.VideosAPI.PostVideosVideoIdSubtitles(context.Background(), videoId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VideosAPIService PutVideosVideoIdAudioTracksLangCode", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var videoId string
		var langCode string

		resp, httpRes, err := apiClient.VideosAPI.PutVideosVideoIdAudioTracksLangCode(context.Background(), videoId, langCode).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VideosAPIService PutVideosVideoIdChapters", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var videoId string

		resp, httpRes, err := apiClient.VideosAPI.PutVideosVideoIdChapters(context.Background(), videoId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VideosAPIService PutVideosVideoIdSubtitlesLangCode", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var videoId string
		var langCode string

		resp, httpRes, err := apiClient.VideosAPI.PutVideosVideoIdSubtitlesLangCode(context.Background(), videoId, langCode).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VideosAPIService PutVideosVideoIdThumbnail", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var videoId string

		resp, httpRes, err := apiClient.VideosAPI.PutVideosVideoIdThumbnail(context.Background(), videoId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
