// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package github_com_qeeqez_api_internal_videos_types

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type ChapterInput struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The start_time_sec property
    start_time_sec *float64
    // The title property
    title *string
}
// NewChapterInput instantiates a new ChapterInput and sets the default values.
func NewChapterInput()(*ChapterInput) {
    m := &ChapterInput{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateChapterInputFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateChapterInputFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewChapterInput(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *ChapterInput) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *ChapterInput) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["start_time_sec"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetFloat64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetStartTimeSec(val)
        }
        return nil
    }
    res["title"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTitle(val)
        }
        return nil
    }
    return res
}
// GetStartTimeSec gets the start_time_sec property value. The start_time_sec property
// returns a *float64 when successful
func (m *ChapterInput) GetStartTimeSec()(*float64) {
    return m.start_time_sec
}
// GetTitle gets the title property value. The title property
// returns a *string when successful
func (m *ChapterInput) GetTitle()(*string) {
    return m.title
}
// Serialize serializes information the current object
func (m *ChapterInput) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteFloat64Value("start_time_sec", m.GetStartTimeSec())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("title", m.GetTitle())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *ChapterInput) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetStartTimeSec sets the start_time_sec property value. The start_time_sec property
func (m *ChapterInput) SetStartTimeSec(value *float64)() {
    m.start_time_sec = value
}
// SetTitle sets the title property value. The title property
func (m *ChapterInput) SetTitle(value *string)() {
    m.title = value
}
type ChapterInputable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetStartTimeSec()(*float64)
    GetTitle()(*string)
    SetStartTimeSec(value *float64)()
    SetTitle(value *string)()
}
