// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package feeds

import (
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// FeedsRequestBuilder builds and executes requests for operations under \feeds
type FeedsRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// ByFeedId gets an item from the github.com/qeeqez/rixl-sdk-go/sdk.feeds.item collection
// returns a *WithFeedItemRequestBuilder when successful
func (m *FeedsRequestBuilder) ByFeedId(feedId string)(*WithFeedItemRequestBuilder) {
    urlTplParams := make(map[string]string)
    for idx, item := range m.BaseRequestBuilder.PathParameters {
        urlTplParams[idx] = item
    }
    if feedId != "" {
        urlTplParams["feedId"] = feedId
    }
    return NewWithFeedItemRequestBuilderInternal(urlTplParams, m.BaseRequestBuilder.RequestAdapter)
}
// NewFeedsRequestBuilderInternal instantiates a new FeedsRequestBuilder and sets the default values.
func NewFeedsRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*FeedsRequestBuilder) {
    m := &FeedsRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/feeds", pathParameters),
    }
    return m
}
// NewFeedsRequestBuilder instantiates a new FeedsRequestBuilder and sets the default values.
func NewFeedsRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*FeedsRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewFeedsRequestBuilderInternal(urlParams, requestAdapter)
}
