// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package feeds

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i12d92dc73d2e9d2b13e50efdbdccd7b0eea209aa4e481b751aa14da12b59bebf "github.com/qeeqez/rixl-sdk-go/sdk/models/github_com_qeeqez_api_internal_errors"
    i8e423a370febfcb59bc134b76fba557a13dffe67d1acc2c98104f520279a913a "github.com/qeeqez/rixl-sdk-go/sdk/models/pagination"
)

// ItemCreatorsWithCreatorItemRequestBuilder builds and executes requests for operations under \feeds\{feedId}\creators\{creatorId}
type ItemCreatorsWithCreatorItemRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// ItemCreatorsWithCreatorItemRequestBuilderGetQueryParameters retrieve posts in a feed by a specific creator, with pagination.
type ItemCreatorsWithCreatorItemRequestBuilderGetQueryParameters struct {
    // Maximum number of items to return in a single request. <br> **Default:** `25`
    Limit *int32 `uriparametername:"limit"`
    // Starting point of the result set. <br>To get page 2 with a limit of 25, set `offset` to `25`. <br> **Default:** `0`
    Offset *int32 `uriparametername:"offset"`
}
// NewItemCreatorsWithCreatorItemRequestBuilderInternal instantiates a new ItemCreatorsWithCreatorItemRequestBuilder and sets the default values.
func NewItemCreatorsWithCreatorItemRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*ItemCreatorsWithCreatorItemRequestBuilder) {
    m := &ItemCreatorsWithCreatorItemRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/feeds/{feedId}/creators/{creatorId}{?limit*,offset*}", pathParameters),
    }
    return m
}
// NewItemCreatorsWithCreatorItemRequestBuilder instantiates a new ItemCreatorsWithCreatorItemRequestBuilder and sets the default values.
func NewItemCreatorsWithCreatorItemRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*ItemCreatorsWithCreatorItemRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewItemCreatorsWithCreatorItemRequestBuilderInternal(urlParams, requestAdapter)
}
// Get retrieve posts in a feed by a specific creator, with pagination.
// returns a PaginatedResponsePostable when successful
// returns a ErrorResponse error when the service returns a 400 status code
// returns a ErrorResponse error when the service returns a 500 status code
func (m *ItemCreatorsWithCreatorItemRequestBuilder) Get(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[ItemCreatorsWithCreatorItemRequestBuilderGetQueryParameters])(i8e423a370febfcb59bc134b76fba557a13dffe67d1acc2c98104f520279a913a.PaginatedResponsePostable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "400": i12d92dc73d2e9d2b13e50efdbdccd7b0eea209aa4e481b751aa14da12b59bebf.CreateErrorResponseFromDiscriminatorValue,
        "500": i12d92dc73d2e9d2b13e50efdbdccd7b0eea209aa4e481b751aa14da12b59bebf.CreateErrorResponseFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, i8e423a370febfcb59bc134b76fba557a13dffe67d1acc2c98104f520279a913a.CreatePaginatedResponsePostFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(i8e423a370febfcb59bc134b76fba557a13dffe67d1acc2c98104f520279a913a.PaginatedResponsePostable), nil
}
// ToGetRequestInformation retrieve posts in a feed by a specific creator, with pagination.
// returns a *RequestInformation when successful
func (m *ItemCreatorsWithCreatorItemRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[ItemCreatorsWithCreatorItemRequestBuilderGetQueryParameters])(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ConfigureRequestInformation(requestInfo, requestConfiguration)
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *ItemCreatorsWithCreatorItemRequestBuilder when successful
func (m *ItemCreatorsWithCreatorItemRequestBuilder) WithUrl(rawUrl string)(*ItemCreatorsWithCreatorItemRequestBuilder) {
    return NewItemCreatorsWithCreatorItemRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
