// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package feeds

import (
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// ItemCreatorsRequestBuilder builds and executes requests for operations under \feeds\{feedId}\creators
type ItemCreatorsRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// ByCreatorId gets an item from the github.com/rixlhq/rixl-go/sdk.feeds.item.creators.item collection
// returns a *ItemCreatorsWithCreatorItemRequestBuilder when successful
func (m *ItemCreatorsRequestBuilder) ByCreatorId(creatorId string)(*ItemCreatorsWithCreatorItemRequestBuilder) {
    urlTplParams := make(map[string]string)
    for idx, item := range m.BaseRequestBuilder.PathParameters {
        urlTplParams[idx] = item
    }
    if creatorId != "" {
        urlTplParams["creatorId"] = creatorId
    }
    return NewItemCreatorsWithCreatorItemRequestBuilderInternal(urlTplParams, m.BaseRequestBuilder.RequestAdapter)
}
// NewItemCreatorsRequestBuilderInternal instantiates a new ItemCreatorsRequestBuilder and sets the default values.
func NewItemCreatorsRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*ItemCreatorsRequestBuilder) {
    m := &ItemCreatorsRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/feeds/{feedId}/creators", pathParameters),
    }
    return m
}
// NewItemCreatorsRequestBuilder instantiates a new ItemCreatorsRequestBuilder and sets the default values.
func NewItemCreatorsRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*ItemCreatorsRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewItemCreatorsRequestBuilderInternal(urlParams, requestAdapter)
}
