/*
RIXL API

**Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.

API version: 2.0
Contact: support@rixl.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package feeds

import (
	"encoding/json"
)

// checks if the UpdateChaptersRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateChaptersRequest{}

// UpdateChaptersRequest struct for UpdateChaptersRequest
type UpdateChaptersRequest struct {
	Chapters []GithubComQeeqezApiInternalVideosTypesChapterInput `json:"chapters,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UpdateChaptersRequest UpdateChaptersRequest

// NewUpdateChaptersRequest instantiates a new UpdateChaptersRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateChaptersRequest() *UpdateChaptersRequest {
	this := UpdateChaptersRequest{}
	return &this
}

// NewUpdateChaptersRequestWithDefaults instantiates a new UpdateChaptersRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateChaptersRequestWithDefaults() *UpdateChaptersRequest {
	this := UpdateChaptersRequest{}
	return &this
}

// GetChapters returns the Chapters field value if set, zero value otherwise.
func (o *UpdateChaptersRequest) GetChapters() []GithubComQeeqezApiInternalVideosTypesChapterInput {
	if o == nil || IsNil(o.Chapters) {
		var ret []GithubComQeeqezApiInternalVideosTypesChapterInput
		return ret
	}
	return o.Chapters
}

// GetChaptersOk returns a tuple with the Chapters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateChaptersRequest) GetChaptersOk() ([]GithubComQeeqezApiInternalVideosTypesChapterInput, bool) {
	if o == nil || IsNil(o.Chapters) {
		return nil, false
	}
	return o.Chapters, true
}

// HasChapters returns a boolean if a field has been set.
func (o *UpdateChaptersRequest) HasChapters() bool {
	if o != nil && !IsNil(o.Chapters) {
		return true
	}

	return false
}

// SetChapters gets a reference to the given []GithubComQeeqezApiInternalVideosTypesChapterInput and assigns it to the Chapters field.
func (o *UpdateChaptersRequest) SetChapters(v []GithubComQeeqezApiInternalVideosTypesChapterInput) {
	o.Chapters = v
}

func (o UpdateChaptersRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateChaptersRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Chapters) {
		toSerialize["chapters"] = o.Chapters
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateChaptersRequest) UnmarshalJSON(data []byte) (err error) {
	varUpdateChaptersRequest := _UpdateChaptersRequest{}

	err = json.Unmarshal(data, &varUpdateChaptersRequest)

	if err != nil {
		return err
	}

	*o = UpdateChaptersRequest(varUpdateChaptersRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "chapters")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateChaptersRequest struct {
	value *UpdateChaptersRequest
	isSet bool
}

func (v NullableUpdateChaptersRequest) Get() *UpdateChaptersRequest {
	return v.value
}

func (v *NullableUpdateChaptersRequest) Set(val *UpdateChaptersRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateChaptersRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateChaptersRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateChaptersRequest(val *UpdateChaptersRequest) *NullableUpdateChaptersRequest {
	return &NullableUpdateChaptersRequest{value: val, isSet: true}
}

func (v NullableUpdateChaptersRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateChaptersRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


