/*
RIXL API

**Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.

API version: 2.0
Contact: support@rixl.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package feeds

import (
	"encoding/json"
)

// checks if the GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest{}

// GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest struct for GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest
type GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest struct {
	VideoId *string `json:"video_id,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest

// NewGithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest instantiates a new GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest() *GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest {
	this := GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest{}
	return &this
}

// NewGithubComQeeqezApiInternalVideosHandlerUploadCompleteRequestWithDefaults instantiates a new GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGithubComQeeqezApiInternalVideosHandlerUploadCompleteRequestWithDefaults() *GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest {
	this := GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest{}
	return &this
}

// GetVideoId returns the VideoId field value if set, zero value otherwise.
func (o *GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest) GetVideoId() string {
	if o == nil || IsNil(o.VideoId) {
		var ret string
		return ret
	}
	return *o.VideoId
}

// GetVideoIdOk returns a tuple with the VideoId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest) GetVideoIdOk() (*string, bool) {
	if o == nil || IsNil(o.VideoId) {
		return nil, false
	}
	return o.VideoId, true
}

// HasVideoId returns a boolean if a field has been set.
func (o *GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest) HasVideoId() bool {
	if o != nil && !IsNil(o.VideoId) {
		return true
	}

	return false
}

// SetVideoId gets a reference to the given string and assigns it to the VideoId field.
func (o *GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest) SetVideoId(v string) {
	o.VideoId = &v
}

func (o GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.VideoId) {
		toSerialize["video_id"] = o.VideoId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest) UnmarshalJSON(data []byte) (err error) {
	varGithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest := _GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest{}

	err = json.Unmarshal(data, &varGithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest)

	if err != nil {
		return err
	}

	*o = GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest(varGithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "video_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest struct {
	value *GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest
	isSet bool
}

func (v NullableGithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest) Get() *GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest {
	return v.value
}

func (v *NullableGithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest) Set(val *GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest(val *GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest) *NullableGithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest {
	return &NullableGithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest{value: val, isSet: true}
}

func (v NullableGithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


