/*
RIXL API

**Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.

API version: 2.0
Contact: support@rixl.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package feeds

import (
	"encoding/json"
)

// checks if the GithubComQeeqezApiInternalErrorsErrorResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GithubComQeeqezApiInternalErrorsErrorResponse{}

// GithubComQeeqezApiInternalErrorsErrorResponse Standard error response returned by the API
type GithubComQeeqezApiInternalErrorsErrorResponse struct {
	// HTTP status code
	Code *int32 `json:"code,omitempty"`
	// Optional details about the error
	Details *string `json:"details,omitempty"`
	// Error message describing what went wrong
	Error *string `json:"error,omitempty"`
}

// NewGithubComQeeqezApiInternalErrorsErrorResponse instantiates a new GithubComQeeqezApiInternalErrorsErrorResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGithubComQeeqezApiInternalErrorsErrorResponse() *GithubComQeeqezApiInternalErrorsErrorResponse {
	this := GithubComQeeqezApiInternalErrorsErrorResponse{}
	return &this
}

// NewGithubComQeeqezApiInternalErrorsErrorResponseWithDefaults instantiates a new GithubComQeeqezApiInternalErrorsErrorResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGithubComQeeqezApiInternalErrorsErrorResponseWithDefaults() *GithubComQeeqezApiInternalErrorsErrorResponse {
	this := GithubComQeeqezApiInternalErrorsErrorResponse{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *GithubComQeeqezApiInternalErrorsErrorResponse) GetCode() int32 {
	if o == nil || IsNil(o.Code) {
		var ret int32
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GithubComQeeqezApiInternalErrorsErrorResponse) GetCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *GithubComQeeqezApiInternalErrorsErrorResponse) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given int32 and assigns it to the Code field.
func (o *GithubComQeeqezApiInternalErrorsErrorResponse) SetCode(v int32) {
	o.Code = &v
}

// GetDetails returns the Details field value if set, zero value otherwise.
func (o *GithubComQeeqezApiInternalErrorsErrorResponse) GetDetails() string {
	if o == nil || IsNil(o.Details) {
		var ret string
		return ret
	}
	return *o.Details
}

// GetDetailsOk returns a tuple with the Details field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GithubComQeeqezApiInternalErrorsErrorResponse) GetDetailsOk() (*string, bool) {
	if o == nil || IsNil(o.Details) {
		return nil, false
	}
	return o.Details, true
}

// HasDetails returns a boolean if a field has been set.
func (o *GithubComQeeqezApiInternalErrorsErrorResponse) HasDetails() bool {
	if o != nil && !IsNil(o.Details) {
		return true
	}

	return false
}

// SetDetails gets a reference to the given string and assigns it to the Details field.
func (o *GithubComQeeqezApiInternalErrorsErrorResponse) SetDetails(v string) {
	o.Details = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *GithubComQeeqezApiInternalErrorsErrorResponse) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GithubComQeeqezApiInternalErrorsErrorResponse) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *GithubComQeeqezApiInternalErrorsErrorResponse) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *GithubComQeeqezApiInternalErrorsErrorResponse) SetError(v string) {
	o.Error = &v
}

func (o GithubComQeeqezApiInternalErrorsErrorResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GithubComQeeqezApiInternalErrorsErrorResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Details) {
		toSerialize["details"] = o.Details
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

type NullableGithubComQeeqezApiInternalErrorsErrorResponse struct {
	value *GithubComQeeqezApiInternalErrorsErrorResponse
	isSet bool
}

func (v NullableGithubComQeeqezApiInternalErrorsErrorResponse) Get() *GithubComQeeqezApiInternalErrorsErrorResponse {
	return v.value
}

func (v *NullableGithubComQeeqezApiInternalErrorsErrorResponse) Set(val *GithubComQeeqezApiInternalErrorsErrorResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGithubComQeeqezApiInternalErrorsErrorResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGithubComQeeqezApiInternalErrorsErrorResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGithubComQeeqezApiInternalErrorsErrorResponse(val *GithubComQeeqezApiInternalErrorsErrorResponse) *NullableGithubComQeeqezApiInternalErrorsErrorResponse {
	return &NullableGithubComQeeqezApiInternalErrorsErrorResponse{value: val, isSet: true}
}

func (v NullableGithubComQeeqezApiInternalErrorsErrorResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGithubComQeeqezApiInternalErrorsErrorResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


