/*
RIXL API

**Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.

API version: 2.0
Contact: support@rixl.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package feeds

import (
	"encoding/json"
)

// checks if the InternalImagesHandlerUploadInitRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InternalImagesHandlerUploadInitRequest{}

// InternalImagesHandlerUploadInitRequest struct for InternalImagesHandlerUploadInitRequest
type InternalImagesHandlerUploadInitRequest struct {
	Format *string `json:"format,omitempty"`
	Name *string `json:"name,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _InternalImagesHandlerUploadInitRequest InternalImagesHandlerUploadInitRequest

// NewInternalImagesHandlerUploadInitRequest instantiates a new InternalImagesHandlerUploadInitRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInternalImagesHandlerUploadInitRequest() *InternalImagesHandlerUploadInitRequest {
	this := InternalImagesHandlerUploadInitRequest{}
	return &this
}

// NewInternalImagesHandlerUploadInitRequestWithDefaults instantiates a new InternalImagesHandlerUploadInitRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInternalImagesHandlerUploadInitRequestWithDefaults() *InternalImagesHandlerUploadInitRequest {
	this := InternalImagesHandlerUploadInitRequest{}
	return &this
}

// GetFormat returns the Format field value if set, zero value otherwise.
func (o *InternalImagesHandlerUploadInitRequest) GetFormat() string {
	if o == nil || IsNil(o.Format) {
		var ret string
		return ret
	}
	return *o.Format
}

// GetFormatOk returns a tuple with the Format field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternalImagesHandlerUploadInitRequest) GetFormatOk() (*string, bool) {
	if o == nil || IsNil(o.Format) {
		return nil, false
	}
	return o.Format, true
}

// HasFormat returns a boolean if a field has been set.
func (o *InternalImagesHandlerUploadInitRequest) HasFormat() bool {
	if o != nil && !IsNil(o.Format) {
		return true
	}

	return false
}

// SetFormat gets a reference to the given string and assigns it to the Format field.
func (o *InternalImagesHandlerUploadInitRequest) SetFormat(v string) {
	o.Format = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *InternalImagesHandlerUploadInitRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternalImagesHandlerUploadInitRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *InternalImagesHandlerUploadInitRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *InternalImagesHandlerUploadInitRequest) SetName(v string) {
	o.Name = &v
}

func (o InternalImagesHandlerUploadInitRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InternalImagesHandlerUploadInitRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Format) {
		toSerialize["format"] = o.Format
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *InternalImagesHandlerUploadInitRequest) UnmarshalJSON(data []byte) (err error) {
	varInternalImagesHandlerUploadInitRequest := _InternalImagesHandlerUploadInitRequest{}

	err = json.Unmarshal(data, &varInternalImagesHandlerUploadInitRequest)

	if err != nil {
		return err
	}

	*o = InternalImagesHandlerUploadInitRequest(varInternalImagesHandlerUploadInitRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "format")
		delete(additionalProperties, "name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableInternalImagesHandlerUploadInitRequest struct {
	value *InternalImagesHandlerUploadInitRequest
	isSet bool
}

func (v NullableInternalImagesHandlerUploadInitRequest) Get() *InternalImagesHandlerUploadInitRequest {
	return v.value
}

func (v *NullableInternalImagesHandlerUploadInitRequest) Set(val *InternalImagesHandlerUploadInitRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableInternalImagesHandlerUploadInitRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableInternalImagesHandlerUploadInitRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInternalImagesHandlerUploadInitRequest(val *InternalImagesHandlerUploadInitRequest) *NullableInternalImagesHandlerUploadInitRequest {
	return &NullableInternalImagesHandlerUploadInitRequest{value: val, isSet: true}
}

func (v NullableInternalImagesHandlerUploadInitRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInternalImagesHandlerUploadInitRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


