/*
RIXL API

**Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.

API version: 2.0
Contact: support@rixl.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package feeds

import (
	"encoding/json"
	"fmt"
)

// FileStatus the model 'FileStatus'
type FileStatus string

// List of FileStatus
const (
	FILESTATUS_FileStatusUploading FileStatus = "uploading"
	FILESTATUS_FileStatusUploaded FileStatus = "uploaded"
	FILESTATUS_FileStatusProcessing FileStatus = "processing"
	FILESTATUS_FileStatusPreparing FileStatus = "preparing"
	FILESTATUS_FileStatusReady FileStatus = "ready"
	FILESTATUS_FileStatusError FileStatus = "error"
)

// All allowed values of FileStatus enum
var AllowedFileStatusEnumValues = []FileStatus{
	"uploading",
	"uploaded",
	"processing",
	"preparing",
	"ready",
	"error",
}

func (v *FileStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := FileStatus(value)
	for _, existing := range AllowedFileStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid FileStatus", value)
}

// NewFileStatusFromValue returns a pointer to a valid FileStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewFileStatusFromValue(v string) (*FileStatus, error) {
	ev := FileStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for FileStatus: valid values are %v", v, AllowedFileStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v FileStatus) IsValid() bool {
	for _, existing := range AllowedFileStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to FileStatus value
func (v FileStatus) Ptr() *FileStatus {
	return &v
}

type NullableFileStatus struct {
	value *FileStatus
	isSet bool
}

func (v NullableFileStatus) Get() *FileStatus {
	return v.value
}

func (v *NullableFileStatus) Set(val *FileStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableFileStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableFileStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFileStatus(val *FileStatus) *NullableFileStatus {
	return &NullableFileStatus{value: val, isSet: true}
}

func (v NullableFileStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFileStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

