/*
RIXL API

**Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.

API version: 2.0
Contact: support@rixl.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package feeds

import (
	"encoding/json"
)

// checks if the InternalImagesHandlerCompleteRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InternalImagesHandlerCompleteRequest{}

// InternalImagesHandlerCompleteRequest struct for InternalImagesHandlerCompleteRequest
type InternalImagesHandlerCompleteRequest struct {
	AttachedToVideo *bool `json:"attached_to_video,omitempty"`
	ImageId *string `json:"image_id,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _InternalImagesHandlerCompleteRequest InternalImagesHandlerCompleteRequest

// NewInternalImagesHandlerCompleteRequest instantiates a new InternalImagesHandlerCompleteRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInternalImagesHandlerCompleteRequest() *InternalImagesHandlerCompleteRequest {
	this := InternalImagesHandlerCompleteRequest{}
	return &this
}

// NewInternalImagesHandlerCompleteRequestWithDefaults instantiates a new InternalImagesHandlerCompleteRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInternalImagesHandlerCompleteRequestWithDefaults() *InternalImagesHandlerCompleteRequest {
	this := InternalImagesHandlerCompleteRequest{}
	return &this
}

// GetAttachedToVideo returns the AttachedToVideo field value if set, zero value otherwise.
func (o *InternalImagesHandlerCompleteRequest) GetAttachedToVideo() bool {
	if o == nil || IsNil(o.AttachedToVideo) {
		var ret bool
		return ret
	}
	return *o.AttachedToVideo
}

// GetAttachedToVideoOk returns a tuple with the AttachedToVideo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternalImagesHandlerCompleteRequest) GetAttachedToVideoOk() (*bool, bool) {
	if o == nil || IsNil(o.AttachedToVideo) {
		return nil, false
	}
	return o.AttachedToVideo, true
}

// HasAttachedToVideo returns a boolean if a field has been set.
func (o *InternalImagesHandlerCompleteRequest) HasAttachedToVideo() bool {
	if o != nil && !IsNil(o.AttachedToVideo) {
		return true
	}

	return false
}

// SetAttachedToVideo gets a reference to the given bool and assigns it to the AttachedToVideo field.
func (o *InternalImagesHandlerCompleteRequest) SetAttachedToVideo(v bool) {
	o.AttachedToVideo = &v
}

// GetImageId returns the ImageId field value if set, zero value otherwise.
func (o *InternalImagesHandlerCompleteRequest) GetImageId() string {
	if o == nil || IsNil(o.ImageId) {
		var ret string
		return ret
	}
	return *o.ImageId
}

// GetImageIdOk returns a tuple with the ImageId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternalImagesHandlerCompleteRequest) GetImageIdOk() (*string, bool) {
	if o == nil || IsNil(o.ImageId) {
		return nil, false
	}
	return o.ImageId, true
}

// HasImageId returns a boolean if a field has been set.
func (o *InternalImagesHandlerCompleteRequest) HasImageId() bool {
	if o != nil && !IsNil(o.ImageId) {
		return true
	}

	return false
}

// SetImageId gets a reference to the given string and assigns it to the ImageId field.
func (o *InternalImagesHandlerCompleteRequest) SetImageId(v string) {
	o.ImageId = &v
}

func (o InternalImagesHandlerCompleteRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InternalImagesHandlerCompleteRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AttachedToVideo) {
		toSerialize["attached_to_video"] = o.AttachedToVideo
	}
	if !IsNil(o.ImageId) {
		toSerialize["image_id"] = o.ImageId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *InternalImagesHandlerCompleteRequest) UnmarshalJSON(data []byte) (err error) {
	varInternalImagesHandlerCompleteRequest := _InternalImagesHandlerCompleteRequest{}

	err = json.Unmarshal(data, &varInternalImagesHandlerCompleteRequest)

	if err != nil {
		return err
	}

	*o = InternalImagesHandlerCompleteRequest(varInternalImagesHandlerCompleteRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "attached_to_video")
		delete(additionalProperties, "image_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableInternalImagesHandlerCompleteRequest struct {
	value *InternalImagesHandlerCompleteRequest
	isSet bool
}

func (v NullableInternalImagesHandlerCompleteRequest) Get() *InternalImagesHandlerCompleteRequest {
	return v.value
}

func (v *NullableInternalImagesHandlerCompleteRequest) Set(val *InternalImagesHandlerCompleteRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableInternalImagesHandlerCompleteRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableInternalImagesHandlerCompleteRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInternalImagesHandlerCompleteRequest(val *InternalImagesHandlerCompleteRequest) *NullableInternalImagesHandlerCompleteRequest {
	return &NullableInternalImagesHandlerCompleteRequest{value: val, isSet: true}
}

func (v NullableInternalImagesHandlerCompleteRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInternalImagesHandlerCompleteRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


