/*
RIXL API

**Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.

API version: 2.0
Contact: support@rixl.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package feeds

import (
	"encoding/json"
)

// checks if the Chapter type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Chapter{}

// Chapter struct for Chapter
type Chapter struct {
	DurationLabel *string `json:"duration_label,omitempty"`
	EndTimeSec *float32 `json:"end_time_sec,omitempty"`
	StartTimeSec *float32 `json:"start_time_sec,omitempty"`
	Title *string `json:"title,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _Chapter Chapter

// NewChapter instantiates a new Chapter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChapter() *Chapter {
	this := Chapter{}
	return &this
}

// NewChapterWithDefaults instantiates a new Chapter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChapterWithDefaults() *Chapter {
	this := Chapter{}
	return &this
}

// GetDurationLabel returns the DurationLabel field value if set, zero value otherwise.
func (o *Chapter) GetDurationLabel() string {
	if o == nil || IsNil(o.DurationLabel) {
		var ret string
		return ret
	}
	return *o.DurationLabel
}

// GetDurationLabelOk returns a tuple with the DurationLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Chapter) GetDurationLabelOk() (*string, bool) {
	if o == nil || IsNil(o.DurationLabel) {
		return nil, false
	}
	return o.DurationLabel, true
}

// HasDurationLabel returns a boolean if a field has been set.
func (o *Chapter) HasDurationLabel() bool {
	if o != nil && !IsNil(o.DurationLabel) {
		return true
	}

	return false
}

// SetDurationLabel gets a reference to the given string and assigns it to the DurationLabel field.
func (o *Chapter) SetDurationLabel(v string) {
	o.DurationLabel = &v
}

// GetEndTimeSec returns the EndTimeSec field value if set, zero value otherwise.
func (o *Chapter) GetEndTimeSec() float32 {
	if o == nil || IsNil(o.EndTimeSec) {
		var ret float32
		return ret
	}
	return *o.EndTimeSec
}

// GetEndTimeSecOk returns a tuple with the EndTimeSec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Chapter) GetEndTimeSecOk() (*float32, bool) {
	if o == nil || IsNil(o.EndTimeSec) {
		return nil, false
	}
	return o.EndTimeSec, true
}

// HasEndTimeSec returns a boolean if a field has been set.
func (o *Chapter) HasEndTimeSec() bool {
	if o != nil && !IsNil(o.EndTimeSec) {
		return true
	}

	return false
}

// SetEndTimeSec gets a reference to the given float32 and assigns it to the EndTimeSec field.
func (o *Chapter) SetEndTimeSec(v float32) {
	o.EndTimeSec = &v
}

// GetStartTimeSec returns the StartTimeSec field value if set, zero value otherwise.
func (o *Chapter) GetStartTimeSec() float32 {
	if o == nil || IsNil(o.StartTimeSec) {
		var ret float32
		return ret
	}
	return *o.StartTimeSec
}

// GetStartTimeSecOk returns a tuple with the StartTimeSec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Chapter) GetStartTimeSecOk() (*float32, bool) {
	if o == nil || IsNil(o.StartTimeSec) {
		return nil, false
	}
	return o.StartTimeSec, true
}

// HasStartTimeSec returns a boolean if a field has been set.
func (o *Chapter) HasStartTimeSec() bool {
	if o != nil && !IsNil(o.StartTimeSec) {
		return true
	}

	return false
}

// SetStartTimeSec gets a reference to the given float32 and assigns it to the StartTimeSec field.
func (o *Chapter) SetStartTimeSec(v float32) {
	o.StartTimeSec = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *Chapter) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Chapter) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *Chapter) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *Chapter) SetTitle(v string) {
	o.Title = &v
}

func (o Chapter) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Chapter) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DurationLabel) {
		toSerialize["duration_label"] = o.DurationLabel
	}
	if !IsNil(o.EndTimeSec) {
		toSerialize["end_time_sec"] = o.EndTimeSec
	}
	if !IsNil(o.StartTimeSec) {
		toSerialize["start_time_sec"] = o.StartTimeSec
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Chapter) UnmarshalJSON(data []byte) (err error) {
	varChapter := _Chapter{}

	err = json.Unmarshal(data, &varChapter)

	if err != nil {
		return err
	}

	*o = Chapter(varChapter)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "duration_label")
		delete(additionalProperties, "end_time_sec")
		delete(additionalProperties, "start_time_sec")
		delete(additionalProperties, "title")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableChapter struct {
	value *Chapter
	isSet bool
}

func (v NullableChapter) Get() *Chapter {
	return v.value
}

func (v *NullableChapter) Set(val *Chapter) {
	v.value = val
	v.isSet = true
}

func (v NullableChapter) IsSet() bool {
	return v.isSet
}

func (v *NullableChapter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChapter(val *Chapter) *NullableChapter {
	return &NullableChapter{value: val, isSet: true}
}

func (v NullableChapter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChapter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


