/*
RIXL API

**Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.

API version: 2.0
Contact: support@rixl.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package feeds

import (
	"encoding/json"
)

// checks if the GithubComQeeqezApiInternalVideosHandlerUploadInitResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GithubComQeeqezApiInternalVideosHandlerUploadInitResponse{}

// GithubComQeeqezApiInternalVideosHandlerUploadInitResponse struct for GithubComQeeqezApiInternalVideosHandlerUploadInitResponse
type GithubComQeeqezApiInternalVideosHandlerUploadInitResponse struct {
	PosterId *string `json:"poster_id,omitempty"`
	PosterPresignedUrl *string `json:"poster_presigned_url,omitempty"`
	UploadExpires *int32 `json:"upload_expires,omitempty"`
	VideoId *string `json:"video_id,omitempty"`
	VideoPresignedUrl *string `json:"video_presigned_url,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GithubComQeeqezApiInternalVideosHandlerUploadInitResponse GithubComQeeqezApiInternalVideosHandlerUploadInitResponse

// NewGithubComQeeqezApiInternalVideosHandlerUploadInitResponse instantiates a new GithubComQeeqezApiInternalVideosHandlerUploadInitResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGithubComQeeqezApiInternalVideosHandlerUploadInitResponse() *GithubComQeeqezApiInternalVideosHandlerUploadInitResponse {
	this := GithubComQeeqezApiInternalVideosHandlerUploadInitResponse{}
	return &this
}

// NewGithubComQeeqezApiInternalVideosHandlerUploadInitResponseWithDefaults instantiates a new GithubComQeeqezApiInternalVideosHandlerUploadInitResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGithubComQeeqezApiInternalVideosHandlerUploadInitResponseWithDefaults() *GithubComQeeqezApiInternalVideosHandlerUploadInitResponse {
	this := GithubComQeeqezApiInternalVideosHandlerUploadInitResponse{}
	return &this
}

// GetPosterId returns the PosterId field value if set, zero value otherwise.
func (o *GithubComQeeqezApiInternalVideosHandlerUploadInitResponse) GetPosterId() string {
	if o == nil || IsNil(o.PosterId) {
		var ret string
		return ret
	}
	return *o.PosterId
}

// GetPosterIdOk returns a tuple with the PosterId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GithubComQeeqezApiInternalVideosHandlerUploadInitResponse) GetPosterIdOk() (*string, bool) {
	if o == nil || IsNil(o.PosterId) {
		return nil, false
	}
	return o.PosterId, true
}

// HasPosterId returns a boolean if a field has been set.
func (o *GithubComQeeqezApiInternalVideosHandlerUploadInitResponse) HasPosterId() bool {
	if o != nil && !IsNil(o.PosterId) {
		return true
	}

	return false
}

// SetPosterId gets a reference to the given string and assigns it to the PosterId field.
func (o *GithubComQeeqezApiInternalVideosHandlerUploadInitResponse) SetPosterId(v string) {
	o.PosterId = &v
}

// GetPosterPresignedUrl returns the PosterPresignedUrl field value if set, zero value otherwise.
func (o *GithubComQeeqezApiInternalVideosHandlerUploadInitResponse) GetPosterPresignedUrl() string {
	if o == nil || IsNil(o.PosterPresignedUrl) {
		var ret string
		return ret
	}
	return *o.PosterPresignedUrl
}

// GetPosterPresignedUrlOk returns a tuple with the PosterPresignedUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GithubComQeeqezApiInternalVideosHandlerUploadInitResponse) GetPosterPresignedUrlOk() (*string, bool) {
	if o == nil || IsNil(o.PosterPresignedUrl) {
		return nil, false
	}
	return o.PosterPresignedUrl, true
}

// HasPosterPresignedUrl returns a boolean if a field has been set.
func (o *GithubComQeeqezApiInternalVideosHandlerUploadInitResponse) HasPosterPresignedUrl() bool {
	if o != nil && !IsNil(o.PosterPresignedUrl) {
		return true
	}

	return false
}

// SetPosterPresignedUrl gets a reference to the given string and assigns it to the PosterPresignedUrl field.
func (o *GithubComQeeqezApiInternalVideosHandlerUploadInitResponse) SetPosterPresignedUrl(v string) {
	o.PosterPresignedUrl = &v
}

// GetUploadExpires returns the UploadExpires field value if set, zero value otherwise.
func (o *GithubComQeeqezApiInternalVideosHandlerUploadInitResponse) GetUploadExpires() int32 {
	if o == nil || IsNil(o.UploadExpires) {
		var ret int32
		return ret
	}
	return *o.UploadExpires
}

// GetUploadExpiresOk returns a tuple with the UploadExpires field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GithubComQeeqezApiInternalVideosHandlerUploadInitResponse) GetUploadExpiresOk() (*int32, bool) {
	if o == nil || IsNil(o.UploadExpires) {
		return nil, false
	}
	return o.UploadExpires, true
}

// HasUploadExpires returns a boolean if a field has been set.
func (o *GithubComQeeqezApiInternalVideosHandlerUploadInitResponse) HasUploadExpires() bool {
	if o != nil && !IsNil(o.UploadExpires) {
		return true
	}

	return false
}

// SetUploadExpires gets a reference to the given int32 and assigns it to the UploadExpires field.
func (o *GithubComQeeqezApiInternalVideosHandlerUploadInitResponse) SetUploadExpires(v int32) {
	o.UploadExpires = &v
}

// GetVideoId returns the VideoId field value if set, zero value otherwise.
func (o *GithubComQeeqezApiInternalVideosHandlerUploadInitResponse) GetVideoId() string {
	if o == nil || IsNil(o.VideoId) {
		var ret string
		return ret
	}
	return *o.VideoId
}

// GetVideoIdOk returns a tuple with the VideoId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GithubComQeeqezApiInternalVideosHandlerUploadInitResponse) GetVideoIdOk() (*string, bool) {
	if o == nil || IsNil(o.VideoId) {
		return nil, false
	}
	return o.VideoId, true
}

// HasVideoId returns a boolean if a field has been set.
func (o *GithubComQeeqezApiInternalVideosHandlerUploadInitResponse) HasVideoId() bool {
	if o != nil && !IsNil(o.VideoId) {
		return true
	}

	return false
}

// SetVideoId gets a reference to the given string and assigns it to the VideoId field.
func (o *GithubComQeeqezApiInternalVideosHandlerUploadInitResponse) SetVideoId(v string) {
	o.VideoId = &v
}

// GetVideoPresignedUrl returns the VideoPresignedUrl field value if set, zero value otherwise.
func (o *GithubComQeeqezApiInternalVideosHandlerUploadInitResponse) GetVideoPresignedUrl() string {
	if o == nil || IsNil(o.VideoPresignedUrl) {
		var ret string
		return ret
	}
	return *o.VideoPresignedUrl
}

// GetVideoPresignedUrlOk returns a tuple with the VideoPresignedUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GithubComQeeqezApiInternalVideosHandlerUploadInitResponse) GetVideoPresignedUrlOk() (*string, bool) {
	if o == nil || IsNil(o.VideoPresignedUrl) {
		return nil, false
	}
	return o.VideoPresignedUrl, true
}

// HasVideoPresignedUrl returns a boolean if a field has been set.
func (o *GithubComQeeqezApiInternalVideosHandlerUploadInitResponse) HasVideoPresignedUrl() bool {
	if o != nil && !IsNil(o.VideoPresignedUrl) {
		return true
	}

	return false
}

// SetVideoPresignedUrl gets a reference to the given string and assigns it to the VideoPresignedUrl field.
func (o *GithubComQeeqezApiInternalVideosHandlerUploadInitResponse) SetVideoPresignedUrl(v string) {
	o.VideoPresignedUrl = &v
}

func (o GithubComQeeqezApiInternalVideosHandlerUploadInitResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GithubComQeeqezApiInternalVideosHandlerUploadInitResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PosterId) {
		toSerialize["poster_id"] = o.PosterId
	}
	if !IsNil(o.PosterPresignedUrl) {
		toSerialize["poster_presigned_url"] = o.PosterPresignedUrl
	}
	if !IsNil(o.UploadExpires) {
		toSerialize["upload_expires"] = o.UploadExpires
	}
	if !IsNil(o.VideoId) {
		toSerialize["video_id"] = o.VideoId
	}
	if !IsNil(o.VideoPresignedUrl) {
		toSerialize["video_presigned_url"] = o.VideoPresignedUrl
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GithubComQeeqezApiInternalVideosHandlerUploadInitResponse) UnmarshalJSON(data []byte) (err error) {
	varGithubComQeeqezApiInternalVideosHandlerUploadInitResponse := _GithubComQeeqezApiInternalVideosHandlerUploadInitResponse{}

	err = json.Unmarshal(data, &varGithubComQeeqezApiInternalVideosHandlerUploadInitResponse)

	if err != nil {
		return err
	}

	*o = GithubComQeeqezApiInternalVideosHandlerUploadInitResponse(varGithubComQeeqezApiInternalVideosHandlerUploadInitResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "poster_id")
		delete(additionalProperties, "poster_presigned_url")
		delete(additionalProperties, "upload_expires")
		delete(additionalProperties, "video_id")
		delete(additionalProperties, "video_presigned_url")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGithubComQeeqezApiInternalVideosHandlerUploadInitResponse struct {
	value *GithubComQeeqezApiInternalVideosHandlerUploadInitResponse
	isSet bool
}

func (v NullableGithubComQeeqezApiInternalVideosHandlerUploadInitResponse) Get() *GithubComQeeqezApiInternalVideosHandlerUploadInitResponse {
	return v.value
}

func (v *NullableGithubComQeeqezApiInternalVideosHandlerUploadInitResponse) Set(val *GithubComQeeqezApiInternalVideosHandlerUploadInitResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGithubComQeeqezApiInternalVideosHandlerUploadInitResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGithubComQeeqezApiInternalVideosHandlerUploadInitResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGithubComQeeqezApiInternalVideosHandlerUploadInitResponse(val *GithubComQeeqezApiInternalVideosHandlerUploadInitResponse) *NullableGithubComQeeqezApiInternalVideosHandlerUploadInitResponse {
	return &NullableGithubComQeeqezApiInternalVideosHandlerUploadInitResponse{value: val, isSet: true}
}

func (v NullableGithubComQeeqezApiInternalVideosHandlerUploadInitResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGithubComQeeqezApiInternalVideosHandlerUploadInitResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


