// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package feeds

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i90c0e1ee53825fe36252e17a45e5d3b5f64ca0be4b2c3a2284950d3439c0ff4d "github.com/rixlhq/rixl-go/sdk/models/github_com_rixlhq_api_internal_errors"
    if5fe6ebdb5303685c58216888d4b27c57bfc171364b5f0d7459d0af798f20bbf "github.com/rixlhq/rixl-go/sdk/models/pagination"
)

// WithFeedItemRequestBuilder builds and executes requests for operations under \feeds\{feedId}
type WithFeedItemRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// WithFeedItemRequestBuilderGetQueryParameters retrieve posts in a feed, with pagination.
type WithFeedItemRequestBuilderGetQueryParameters struct {
    // Maximum number of items to return in a single request. <br> **Default:** `25`
    Limit *int32 `uriparametername:"limit"`
    // Starting point of the result set. <br>To get page 2 with a limit of 25, set `offset` to `25`. <br> **Default:** `0`
    Offset *int32 `uriparametername:"offset"`
}
// ByPostId gets an item from the github.com/rixlhq/rixl-go/sdk.feeds.item.item collection
// returns a *ItemWithPostItemRequestBuilder when successful
func (m *WithFeedItemRequestBuilder) ByPostId(postId string)(*ItemWithPostItemRequestBuilder) {
    urlTplParams := make(map[string]string)
    for idx, item := range m.BaseRequestBuilder.PathParameters {
        urlTplParams[idx] = item
    }
    if postId != "" {
        urlTplParams["postId"] = postId
    }
    return NewItemWithPostItemRequestBuilderInternal(urlTplParams, m.BaseRequestBuilder.RequestAdapter)
}
// NewWithFeedItemRequestBuilderInternal instantiates a new WithFeedItemRequestBuilder and sets the default values.
func NewWithFeedItemRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*WithFeedItemRequestBuilder) {
    m := &WithFeedItemRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/feeds/{feedId}{?limit*,offset*}", pathParameters),
    }
    return m
}
// NewWithFeedItemRequestBuilder instantiates a new WithFeedItemRequestBuilder and sets the default values.
func NewWithFeedItemRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*WithFeedItemRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewWithFeedItemRequestBuilderInternal(urlParams, requestAdapter)
}
// Creators the creators property
// returns a *ItemCreatorsRequestBuilder when successful
func (m *WithFeedItemRequestBuilder) Creators()(*ItemCreatorsRequestBuilder) {
    return NewItemCreatorsRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// Get retrieve posts in a feed, with pagination.
// returns a PaginatedResponsePostable when successful
// returns a ErrorResponse error when the service returns a 400 status code
// returns a ErrorResponse error when the service returns a 500 status code
func (m *WithFeedItemRequestBuilder) Get(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[WithFeedItemRequestBuilderGetQueryParameters])(if5fe6ebdb5303685c58216888d4b27c57bfc171364b5f0d7459d0af798f20bbf.PaginatedResponsePostable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "400": i90c0e1ee53825fe36252e17a45e5d3b5f64ca0be4b2c3a2284950d3439c0ff4d.CreateErrorResponseFromDiscriminatorValue,
        "500": i90c0e1ee53825fe36252e17a45e5d3b5f64ca0be4b2c3a2284950d3439c0ff4d.CreateErrorResponseFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, if5fe6ebdb5303685c58216888d4b27c57bfc171364b5f0d7459d0af798f20bbf.CreatePaginatedResponsePostFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(if5fe6ebdb5303685c58216888d4b27c57bfc171364b5f0d7459d0af798f20bbf.PaginatedResponsePostable), nil
}
// ToGetRequestInformation retrieve posts in a feed, with pagination.
// returns a *RequestInformation when successful
func (m *WithFeedItemRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[WithFeedItemRequestBuilderGetQueryParameters])(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ConfigureRequestInformation(requestInfo, requestConfiguration)
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *WithFeedItemRequestBuilder when successful
func (m *WithFeedItemRequestBuilder) WithUrl(rawUrl string)(*WithFeedItemRequestBuilder) {
    return NewWithFeedItemRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
