// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type AudioTrack struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The created_at property
    created_at *string
    // The format property
    format *string
    // The id property
    id *string
    // The label property
    label *string
    // The language_code property
    language_code *string
    // The name property
    name *string
    // The size property
    size *int32
    // The url property
    url *string
    // The video_id property
    video_id *string
}
// NewAudioTrack instantiates a new AudioTrack and sets the default values.
func NewAudioTrack()(*AudioTrack) {
    m := &AudioTrack{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateAudioTrackFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateAudioTrackFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewAudioTrack(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *AudioTrack) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetCreatedAt gets the created_at property value. The created_at property
// returns a *string when successful
func (m *AudioTrack) GetCreatedAt()(*string) {
    return m.created_at
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *AudioTrack) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["created_at"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCreatedAt(val)
        }
        return nil
    }
    res["format"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetFormat(val)
        }
        return nil
    }
    res["id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetId(val)
        }
        return nil
    }
    res["label"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLabel(val)
        }
        return nil
    }
    res["language_code"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLanguageCode(val)
        }
        return nil
    }
    res["name"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetName(val)
        }
        return nil
    }
    res["size"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSize(val)
        }
        return nil
    }
    res["url"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetUrl(val)
        }
        return nil
    }
    res["video_id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetVideoId(val)
        }
        return nil
    }
    return res
}
// GetFormat gets the format property value. The format property
// returns a *string when successful
func (m *AudioTrack) GetFormat()(*string) {
    return m.format
}
// GetId gets the id property value. The id property
// returns a *string when successful
func (m *AudioTrack) GetId()(*string) {
    return m.id
}
// GetLabel gets the label property value. The label property
// returns a *string when successful
func (m *AudioTrack) GetLabel()(*string) {
    return m.label
}
// GetLanguageCode gets the language_code property value. The language_code property
// returns a *string when successful
func (m *AudioTrack) GetLanguageCode()(*string) {
    return m.language_code
}
// GetName gets the name property value. The name property
// returns a *string when successful
func (m *AudioTrack) GetName()(*string) {
    return m.name
}
// GetSize gets the size property value. The size property
// returns a *int32 when successful
func (m *AudioTrack) GetSize()(*int32) {
    return m.size
}
// GetUrl gets the url property value. The url property
// returns a *string when successful
func (m *AudioTrack) GetUrl()(*string) {
    return m.url
}
// GetVideoId gets the video_id property value. The video_id property
// returns a *string when successful
func (m *AudioTrack) GetVideoId()(*string) {
    return m.video_id
}
// Serialize serializes information the current object
func (m *AudioTrack) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("created_at", m.GetCreatedAt())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("format", m.GetFormat())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("id", m.GetId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("label", m.GetLabel())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("language_code", m.GetLanguageCode())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("name", m.GetName())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("size", m.GetSize())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("url", m.GetUrl())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("video_id", m.GetVideoId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *AudioTrack) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetCreatedAt sets the created_at property value. The created_at property
func (m *AudioTrack) SetCreatedAt(value *string)() {
    m.created_at = value
}
// SetFormat sets the format property value. The format property
func (m *AudioTrack) SetFormat(value *string)() {
    m.format = value
}
// SetId sets the id property value. The id property
func (m *AudioTrack) SetId(value *string)() {
    m.id = value
}
// SetLabel sets the label property value. The label property
func (m *AudioTrack) SetLabel(value *string)() {
    m.label = value
}
// SetLanguageCode sets the language_code property value. The language_code property
func (m *AudioTrack) SetLanguageCode(value *string)() {
    m.language_code = value
}
// SetName sets the name property value. The name property
func (m *AudioTrack) SetName(value *string)() {
    m.name = value
}
// SetSize sets the size property value. The size property
func (m *AudioTrack) SetSize(value *int32)() {
    m.size = value
}
// SetUrl sets the url property value. The url property
func (m *AudioTrack) SetUrl(value *string)() {
    m.url = value
}
// SetVideoId sets the video_id property value. The video_id property
func (m *AudioTrack) SetVideoId(value *string)() {
    m.video_id = value
}
type AudioTrackable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetCreatedAt()(*string)
    GetFormat()(*string)
    GetId()(*string)
    GetLabel()(*string)
    GetLanguageCode()(*string)
    GetName()(*string)
    GetSize()(*int32)
    GetUrl()(*string)
    GetVideoId()(*string)
    SetCreatedAt(value *string)()
    SetFormat(value *string)()
    SetId(value *string)()
    SetLabel(value *string)()
    SetLanguageCode(value *string)()
    SetName(value *string)()
    SetSize(value *int32)()
    SetUrl(value *string)()
    SetVideoId(value *string)()
}
