// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type Image struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The attached_to_video property
    attached_to_video *bool
    // The file property
    file Fileable
    // The height property
    height *int32
    // The id property
    id *string
    // The thumbhash property
    thumbhash *string
    // The width property
    width *int32
}
// NewImage instantiates a new Image and sets the default values.
func NewImage()(*Image) {
    m := &Image{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateImageFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateImageFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewImage(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *Image) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetAttachedToVideo gets the attached_to_video property value. The attached_to_video property
// returns a *bool when successful
func (m *Image) GetAttachedToVideo()(*bool) {
    return m.attached_to_video
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *Image) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["attached_to_video"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAttachedToVideo(val)
        }
        return nil
    }
    res["file"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateFileFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetFile(val.(Fileable))
        }
        return nil
    }
    res["height"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetHeight(val)
        }
        return nil
    }
    res["id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetId(val)
        }
        return nil
    }
    res["thumbhash"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetThumbhash(val)
        }
        return nil
    }
    res["width"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetWidth(val)
        }
        return nil
    }
    return res
}
// GetFile gets the file property value. The file property
// returns a Fileable when successful
func (m *Image) GetFile()(Fileable) {
    return m.file
}
// GetHeight gets the height property value. The height property
// returns a *int32 when successful
func (m *Image) GetHeight()(*int32) {
    return m.height
}
// GetId gets the id property value. The id property
// returns a *string when successful
func (m *Image) GetId()(*string) {
    return m.id
}
// GetThumbhash gets the thumbhash property value. The thumbhash property
// returns a *string when successful
func (m *Image) GetThumbhash()(*string) {
    return m.thumbhash
}
// GetWidth gets the width property value. The width property
// returns a *int32 when successful
func (m *Image) GetWidth()(*int32) {
    return m.width
}
// Serialize serializes information the current object
func (m *Image) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteBoolValue("attached_to_video", m.GetAttachedToVideo())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("file", m.GetFile())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("height", m.GetHeight())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("id", m.GetId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("thumbhash", m.GetThumbhash())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("width", m.GetWidth())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *Image) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetAttachedToVideo sets the attached_to_video property value. The attached_to_video property
func (m *Image) SetAttachedToVideo(value *bool)() {
    m.attached_to_video = value
}
// SetFile sets the file property value. The file property
func (m *Image) SetFile(value Fileable)() {
    m.file = value
}
// SetHeight sets the height property value. The height property
func (m *Image) SetHeight(value *int32)() {
    m.height = value
}
// SetId sets the id property value. The id property
func (m *Image) SetId(value *string)() {
    m.id = value
}
// SetThumbhash sets the thumbhash property value. The thumbhash property
func (m *Image) SetThumbhash(value *string)() {
    m.thumbhash = value
}
// SetWidth sets the width property value. The width property
func (m *Image) SetWidth(value *int32)() {
    m.width = value
}
type Imageable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAttachedToVideo()(*bool)
    GetFile()(Fileable)
    GetHeight()(*int32)
    GetId()(*string)
    GetThumbhash()(*string)
    GetWidth()(*int32)
    SetAttachedToVideo(value *bool)()
    SetFile(value Fileable)()
    SetHeight(value *int32)()
    SetId(value *string)()
    SetThumbhash(value *string)()
    SetWidth(value *int32)()
}
