// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
type PostType int

const (
    IMAGE_POSTTYPE PostType = iota
    VIDEO_POSTTYPE
)

func (i PostType) String() string {
    return []string{"image", "video"}[i]
}
func ParsePostType(v string) (any, error) {
    result := IMAGE_POSTTYPE
    switch v {
        case "image":
            result = IMAGE_POSTTYPE
        case "video":
            result = VIDEO_POSTTYPE
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializePostType(values []PostType) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i PostType) isMultiValue() bool {
    return false
}
