// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type UpdateChaptersResponse struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The chapters property
    chapters []Chapterable
    // The video_id property
    video_id *string
}
// NewUpdateChaptersResponse instantiates a new UpdateChaptersResponse and sets the default values.
func NewUpdateChaptersResponse()(*UpdateChaptersResponse) {
    m := &UpdateChaptersResponse{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateUpdateChaptersResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateUpdateChaptersResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewUpdateChaptersResponse(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *UpdateChaptersResponse) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetChapters gets the chapters property value. The chapters property
// returns a []Chapterable when successful
func (m *UpdateChaptersResponse) GetChapters()([]Chapterable) {
    return m.chapters
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *UpdateChaptersResponse) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["chapters"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreateChapterFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]Chapterable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(Chapterable)
                }
            }
            m.SetChapters(res)
        }
        return nil
    }
    res["video_id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetVideoId(val)
        }
        return nil
    }
    return res
}
// GetVideoId gets the video_id property value. The video_id property
// returns a *string when successful
func (m *UpdateChaptersResponse) GetVideoId()(*string) {
    return m.video_id
}
// Serialize serializes information the current object
func (m *UpdateChaptersResponse) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetChapters() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetChapters()))
        for i, v := range m.GetChapters() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err := writer.WriteCollectionOfObjectValues("chapters", cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("video_id", m.GetVideoId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *UpdateChaptersResponse) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetChapters sets the chapters property value. The chapters property
func (m *UpdateChaptersResponse) SetChapters(value []Chapterable)() {
    m.chapters = value
}
// SetVideoId sets the video_id property value. The video_id property
func (m *UpdateChaptersResponse) SetVideoId(value *string)() {
    m.video_id = value
}
type UpdateChaptersResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetChapters()([]Chapterable)
    GetVideoId()(*string)
    SetChapters(value []Chapterable)()
    SetVideoId(value *string)()
}
