// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// VideoUploadInitRequest video upload initialization request
type VideoUploadInitRequest struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The file_name property
    file_name *string
    // The image_format property
    image_format *string
}
// NewVideoUploadInitRequest instantiates a new VideoUploadInitRequest and sets the default values.
func NewVideoUploadInitRequest()(*VideoUploadInitRequest) {
    m := &VideoUploadInitRequest{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateVideoUploadInitRequestFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateVideoUploadInitRequestFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewVideoUploadInitRequest(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *VideoUploadInitRequest) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *VideoUploadInitRequest) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["file_name"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetFileName(val)
        }
        return nil
    }
    res["image_format"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetImageFormat(val)
        }
        return nil
    }
    return res
}
// GetFileName gets the file_name property value. The file_name property
// returns a *string when successful
func (m *VideoUploadInitRequest) GetFileName()(*string) {
    return m.file_name
}
// GetImageFormat gets the image_format property value. The image_format property
// returns a *string when successful
func (m *VideoUploadInitRequest) GetImageFormat()(*string) {
    return m.image_format
}
// Serialize serializes information the current object
func (m *VideoUploadInitRequest) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("file_name", m.GetFileName())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("image_format", m.GetImageFormat())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *VideoUploadInitRequest) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetFileName sets the file_name property value. The file_name property
func (m *VideoUploadInitRequest) SetFileName(value *string)() {
    m.file_name = value
}
// SetImageFormat sets the image_format property value. The image_format property
func (m *VideoUploadInitRequest) SetImageFormat(value *string)() {
    m.image_format = value
}
type VideoUploadInitRequestable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetFileName()(*string)
    GetImageFormat()(*string)
    SetFileName(value *string)()
    SetImageFormat(value *string)()
}
