/*
RIXL API

Testing FeedsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package feeds

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_feeds_FeedsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test FeedsAPIService GetFeedsFeedId", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var feedId string

		resp, httpRes, err := apiClient.FeedsAPI.GetFeedsFeedId(context.Background(), feedId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FeedsAPIService GetFeedsFeedIdCreatorsCreatorId", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var feedId string
		var creatorId string

		resp, httpRes, err := apiClient.FeedsAPI.GetFeedsFeedIdCreatorsCreatorId(context.Background(), feedId, creatorId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FeedsAPIService GetFeedsFeedIdPostId", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var feedId string
		var postId string

		resp, httpRes, err := apiClient.FeedsAPI.GetFeedsFeedIdPostId(context.Background(), feedId, postId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
