// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package internal_images_handler

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type InitResponse struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The image_id property
    image_id *string
    // The presigned_url property
    presigned_url *string
    // The upload_expires property
    upload_expires *int32
}
// NewInitResponse instantiates a new InitResponse and sets the default values.
func NewInitResponse()(*InitResponse) {
    m := &InitResponse{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateInitResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateInitResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewInitResponse(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *InitResponse) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *InitResponse) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["image_id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetImageId(val)
        }
        return nil
    }
    res["presigned_url"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPresignedUrl(val)
        }
        return nil
    }
    res["upload_expires"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetUploadExpires(val)
        }
        return nil
    }
    return res
}
// GetImageId gets the image_id property value. The image_id property
// returns a *string when successful
func (m *InitResponse) GetImageId()(*string) {
    return m.image_id
}
// GetPresignedUrl gets the presigned_url property value. The presigned_url property
// returns a *string when successful
func (m *InitResponse) GetPresignedUrl()(*string) {
    return m.presigned_url
}
// GetUploadExpires gets the upload_expires property value. The upload_expires property
// returns a *int32 when successful
func (m *InitResponse) GetUploadExpires()(*int32) {
    return m.upload_expires
}
// Serialize serializes information the current object
func (m *InitResponse) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("image_id", m.GetImageId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("presigned_url", m.GetPresignedUrl())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("upload_expires", m.GetUploadExpires())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *InitResponse) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetImageId sets the image_id property value. The image_id property
func (m *InitResponse) SetImageId(value *string)() {
    m.image_id = value
}
// SetPresignedUrl sets the presigned_url property value. The presigned_url property
func (m *InitResponse) SetPresignedUrl(value *string)() {
    m.presigned_url = value
}
// SetUploadExpires sets the upload_expires property value. The upload_expires property
func (m *InitResponse) SetUploadExpires(value *int32)() {
    m.upload_expires = value
}
type InitResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetImageId()(*string)
    GetPresignedUrl()(*string)
    GetUploadExpires()(*int32)
    SetImageId(value *string)()
    SetPresignedUrl(value *string)()
    SetUploadExpires(value *int32)()
}
