// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package pagination

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
    i6a8119714aaa1c348f0ce22bc9a01a8501620888990eb654e94c882e51a080ed "github.com/qeeqez/rixl-sdk-go/sdk/models"
)

type PaginatedResponsePost struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // Data contains the slice of items for the current request.
    data []i6a8119714aaa1c348f0ce22bc9a01a8501620888990eb654e94c882e51a080ed.Postable
    // Pagination data for the request.
    pagination Paginationable
}
// NewPaginatedResponsePost instantiates a new PaginatedResponsePost and sets the default values.
func NewPaginatedResponsePost()(*PaginatedResponsePost) {
    m := &PaginatedResponsePost{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreatePaginatedResponsePostFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreatePaginatedResponsePostFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewPaginatedResponsePost(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *PaginatedResponsePost) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetData gets the data property value. Data contains the slice of items for the current request.
// returns a []Postable when successful
func (m *PaginatedResponsePost) GetData()([]i6a8119714aaa1c348f0ce22bc9a01a8501620888990eb654e94c882e51a080ed.Postable) {
    return m.data
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *PaginatedResponsePost) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["data"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(i6a8119714aaa1c348f0ce22bc9a01a8501620888990eb654e94c882e51a080ed.CreatePostFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]i6a8119714aaa1c348f0ce22bc9a01a8501620888990eb654e94c882e51a080ed.Postable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(i6a8119714aaa1c348f0ce22bc9a01a8501620888990eb654e94c882e51a080ed.Postable)
                }
            }
            m.SetData(res)
        }
        return nil
    }
    res["pagination"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreatePaginationFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPagination(val.(Paginationable))
        }
        return nil
    }
    return res
}
// GetPagination gets the pagination property value. Pagination data for the request.
// returns a Paginationable when successful
func (m *PaginatedResponsePost) GetPagination()(Paginationable) {
    return m.pagination
}
// Serialize serializes information the current object
func (m *PaginatedResponsePost) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetData() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetData()))
        for i, v := range m.GetData() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err := writer.WriteCollectionOfObjectValues("data", cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("pagination", m.GetPagination())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *PaginatedResponsePost) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetData sets the data property value. Data contains the slice of items for the current request.
func (m *PaginatedResponsePost) SetData(value []i6a8119714aaa1c348f0ce22bc9a01a8501620888990eb654e94c882e51a080ed.Postable)() {
    m.data = value
}
// SetPagination sets the pagination property value. Pagination data for the request.
func (m *PaginatedResponsePost) SetPagination(value Paginationable)() {
    m.pagination = value
}
type PaginatedResponsePostable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetData()([]i6a8119714aaa1c348f0ce22bc9a01a8501620888990eb654e94c882e51a080ed.Postable)
    GetPagination()(Paginationable)
    SetData(value []i6a8119714aaa1c348f0ce22bc9a01a8501620888990eb654e94c882e51a080ed.Postable)()
    SetPagination(value Paginationable)()
}
