// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package pagination

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Pagination pagination data for the request.
type Pagination struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // Maximum number of items to return in a single request.
    limit *int32
    // Starting point of the result set.
    offset *int32
    // The total number of available items in the full list.
    total *int32
}
// NewPagination instantiates a new Pagination and sets the default values.
func NewPagination()(*Pagination) {
    m := &Pagination{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreatePaginationFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreatePaginationFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewPagination(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *Pagination) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *Pagination) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["limit"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLimit(val)
        }
        return nil
    }
    res["offset"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetOffset(val)
        }
        return nil
    }
    res["total"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTotal(val)
        }
        return nil
    }
    return res
}
// GetLimit gets the limit property value. Maximum number of items to return in a single request.
// returns a *int32 when successful
func (m *Pagination) GetLimit()(*int32) {
    return m.limit
}
// GetOffset gets the offset property value. Starting point of the result set.
// returns a *int32 when successful
func (m *Pagination) GetOffset()(*int32) {
    return m.offset
}
// GetTotal gets the total property value. The total number of available items in the full list.
// returns a *int32 when successful
func (m *Pagination) GetTotal()(*int32) {
    return m.total
}
// Serialize serializes information the current object
func (m *Pagination) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteInt32Value("limit", m.GetLimit())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("offset", m.GetOffset())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("total", m.GetTotal())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *Pagination) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetLimit sets the limit property value. Maximum number of items to return in a single request.
func (m *Pagination) SetLimit(value *int32)() {
    m.limit = value
}
// SetOffset sets the offset property value. Starting point of the result set.
func (m *Pagination) SetOffset(value *int32)() {
    m.offset = value
}
// SetTotal sets the total property value. The total number of available items in the full list.
func (m *Pagination) SetTotal(value *int32)() {
    m.total = value
}
type Paginationable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetLimit()(*int32)
    GetOffset()(*int32)
    GetTotal()(*int32)
    SetLimit(value *int32)()
    SetOffset(value *int32)()
    SetTotal(value *int32)()
}
